const m = ({
  id,
  title,
  year,
  universe,
  category,
  franchise,
  genre,
  rating,
  poster,
  plot,
  cast,
  streaming,
  runtime,
  notes,
}) => ({
  id,
  title,
  year,
  universe,
  category,
  franchise,
  genre,
  rating,
  poster,
  plot,
  cast,
  streaming,
  runtime,
  notes,
});
export const mediaItems = [
  /* ---------- STAR WARS MOVIES ---------- */
  m({
    "id": "sw-iv",
    "title": "Star Wars: Episode IV – A New Hope",
    "year": "1977",
    "year": "1977",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Original Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 8.6,
    "streaming": ["Disney+"],
    "plot": "Luke Skywalker leaves Tatooine and joins the Rebel Alliance to destroy the Death Star.",
    "poster": "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"]
  }),
  m({
    "id": "sw-v",
    "title": "Star Wars: Episode V – The Empire Strikes Back",
    "year": "1980",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Original Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 8.7,
    "streaming": ["Disney+"],
    "poster": "https://image.tmdb.org/t/p/w500/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
    "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"]
  }),
  m({
    "id": "sw-vi",
    "title": "Star Wars: Episode VI – Return of the Jedi",
    "year": "1983",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Original Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 8.3,
    "streaming": ["Disney+"],
    "poster": "https://image.tmdb.org/t/p/w500/mDCBQNhR6R0PVFucJl0O4Hp5klZ.jpg",
    "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"]
  }),
  m({
    "id": "sw-i",
    "title": "Star Wars: Episode I – The Phantom Menace",
    "year": "1999",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Prequel Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 6.5,
    "streaming": ["Disney+"],
    "poster": "https://image.tmdb.org/t/p/w500/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
    "cast": ["Liam Neeson", "Ewan McGregor", "Natalie Portman", "Jake Lloyd"]
  }),
  m({
    "id": "sw-ii",
    "title": "Star Wars: Episode II – Attack of the Clones",
    "year": "2002",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Prequel Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 6.6,
    "streaming": ["Disney+"],
    "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/oZNPzxqM2s5DyVWab09NTQScDQt.jpg",
    "cast": ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Christopher Lee"]
  }),
  m({
    "id": "sw-iii",
    "title": "Star Wars: Episode III – Revenge of the Sith",
    "year": "2005",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Prequel Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 7.6,
    "streaming": ["Disney+"],
    "poster": "https://image.tmdb.org/t/p/w500/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg",
    "cast": ["Hayden Christensen", "Ewan McGregor", "Natalie Portman", "Samuel L. Jackson"]
  }),
  m({
    "id": "sw-vii",
    "title": "Star Wars: Episode VII – The Force Awakens",
    "year": "2015",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Sequel Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 7.8,
    "streaming": ["Disney+"],
    "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
    "cast": ["Daisy Ridley", "John Boyega", "Adam Driver", "Harrison Ford"]
  }),
  m({
    "id": "sw-viii",
    "title": "Star Wars: Episode VIII – The Last Jedi",
    "year": "2017",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Sequel Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 6.9,
    "streaming": ["Disney+"],
    "poster": "https://image.tmdb.org/t/p/w500/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    "cast": ["Mark Hamill", "Carrie Fisher", "Adam Driver", "Daisy Ridley"]
  }),
  m({
    "id": "sw-ix",
    "title": "Star Wars: Episode IX – The Rise of Skywalker",
    "year": "2019",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Sequel Trilogy",
    "genre": "Sci-Fi / Adventure",
    "rating": 6.4,
    "streaming": ["Disney+"],
    "poster": "https://image.tmdb.org/t/p/w500/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    "cast": ["Daisy Ridley", "Adam Driver", "John Boyega", "Oscar Isaac"]
  }),
  m({
    "id": "sw-rogue-one",
    "title": "Rogue One: A Star Wars Story",
    "year": "2016",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Anthology",
    "genre": "Sci-Fi / War",
    "rating": 8.0,
    "streaming": ["Disney+"],
    "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg",
    "cast": ["Felicity Jones", "Diego Luna", "Ben Mendelsohn", "Alan Tudyk"]
  }),
  m({
    "id": "sw-solo",
    "title": "Solo: A Star Wars Story",
    "year": "2018",
    "universe": "Star Wars",
    "category": "movie",
    "franchise": "Anthology",
    "genre": "Sci-Fi / Adventure",
    "rating": 6.9,
    "streaming": ["Disney+"],
    "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/4oD6VEccFkorEBTEDXtpLAaz0Rl.jpg",
    "cast": ["Alden Ehrenreich", "Woody Harrelson", "Emilia Clarke", "Donald Glover"]
  }),
  // INDIANA JONES "MOVIES":  
  m({
    "id": "ij-raiders",
    "title": "Raiders of the Lost Ark",
    "year": "1981",
    "universe": "Indiana Jones",
    "category": "movie",
    "franchise": "Indiana Jones",
    "genre": "Adventure / Action",
    "rating": 8.4,
    "streaming": ["Disney+", "Paramount+"],
    "poster": "https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    "cast": ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies"]
  }),
  m({
    "id": "ij-temple",
    "title": "Indiana Jones and the Temple of Doom",
    "year": "1984",
    "universe": "Indiana Jones",
    "category": "movie",
    "franchise": "Indiana Jones",
    "genre": "Adventure / Action",
    "rating": 7.5,
    "streaming": ["Disney+", "Paramount+"],
    "poster": "https://www.themoviedb.org/t/p/w1280/gpdVNUaa4LhRMLfJOPj1AZdhAZ3.jpg",
    "cast": ["Harrison Ford", "Kate Capshaw", "Ke Huy Quan", "Amrish Puri"]
  }),
  m({
    "id": "ij-crusade",
    "title": "Indiana Jones and the Last Crusade",
    "year": "1989",
    "universe": "Indiana Jones",
    "category": "movie",
    "franchise": "Indiana Jones",
    "genre": "Adventure / Action",
    "rating": 8.2,
    "streaming": ["Disney+", "Paramount+"],
    "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/sizg1AU8f8JDZX4QIgE4pjUMBvx.jpg",
    "cast": ["Harrison Ford", "Sean Connery", "Denholm Elliott", "Alison Doody"]
  }),
  m({
    "id": "ij-crystal-skull",
    "title": "Indiana Jones and the Kingdom of the Crystal Skull",
    "year": "2008",
    "universe": "Indiana Jones",
    "category": "movie",
    "franchise": "Indiana Jones",
    "genre": "Adventure / Action",
    "rating": 6.1,
    "streaming": ["Disney+", "Paramount+"],
    "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/56As6XEM1flWvprX4LgkPl8ii4K.jpg",
    "cast": ["Harrison Ford", "Cate Blanchett", "Shia LaBeouf", "Karen Allen"]
  }),
m({
  "id": "ij-dial-destiny",
  "title": "Indiana Jones and the Dial of Destiny",
  "year": "2023",
  "universe": "Indiana Jones",
  "category": "movie",
  "franchise": "Indiana Jones",
  "genre": "Adventure / Action",
  "rating": 6.5,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
  "cast": ["Harrison Ford","Phoebe Waller-Bridge","Mads Mikkelsen","Antonio Banderas"]
}),
m({
  "id": "mcu-iron-man-1",
  "title": "Iron Man",
  "year": "2008",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 1",
  "genre": "Action / Superhero",
  "rating": 7.9,
  "streaming": ["Disney+"],
  "plot": "Tony Stark builds an armored suit and becomes Iron Man.",
  "poster": "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
  "cast": ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges", "Terrence Howard"]
}),

m({
  "id": "mcu-hulk",
  "title": "The Incredible Hulk (2008)",
  "year": "2008",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 1",
  "genre": "Action / Superhero",
  "rating": 6.7,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
  "cast": ["Edward Norton", "Liv Tyler", "Tim Roth", "William Hurt"]
}),
m({
  "id": "mcu-iron-man-2",
  "title": "Iron Man 2",
  "year": "2010",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 1",
  "genre": "Action / Superhero",
  "rating": 7.0,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
  "cast": ["Robert Downey Jr.", "Gwyneth Paltrow", "Scarlett Johansson", "Sam Rockwell"]
}),
m({
  "id": "mcu-thor-1",
  "title": "Thor",
  "year": "2011",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 1",
  "genre": "Action / Fantasy",
  "rating": 7.0,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
  "cast": ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston", "Anthony Hopkins"]
}),
m({
  "id": "mcu-cap-first",
  "title": "Captain America: The First Avenger",
  "year": "2011",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 1",
  "genre": "Action / Superhero",
  "rating": 7.2,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
  "cast": ["Chris Evans", "Hayley Atwell", "Sebastian Stan", "Tommy Lee Jones"]
}),
m({
  "id": "mcu-avengers-1",
  "title": "Marvel’s The Avengers",
  "year": "2012",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 1",
  "genre": "Action / Superhero",
  "rating": 8.0,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
  "cast": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson", "Chris Hemsworth", "Mark Ruffalo"]
}),
m({
  "id": "mcu-iron-man-3",
  "title": "Iron Man 3",
  "year": "2013",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 2",
  "genre": "Action / Superhero",
  "rating": 7.1,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
  "cast": ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Ben Kingsley"]
}),
m({
  "id": "mcu-thor-2",
  "title": "Thor: The Dark World",
  "year": "2013",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 2",
  "genre": "Action / Fantasy",
  "rating": 6.7,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
  "cast": ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston", "Christopher Eccleston"]
}),
m({
  "id": "mcu-cap-winter",
  "title": "Captain America: The Winter Soldier",
  "year": "2014",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 2",
  "genre": "Action / Thriller",
  "rating": 7.7,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
  "cast": ["Chris Evans", "Scarlett Johansson", "Sebastian Stan", "Anthony Mackie"]
}),
m({
  "id": "mcu-gotg-1",
  "title": "Guardians of the Galaxy",
  "year": "2014",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 2",
  "genre": "Sci-Fi / Comedy",
  "rating": 8.0,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
  "cast": ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Bradley Cooper", "Vin Diesel"]
}),
m({
  "id": "mcu-age-ultron",
  "title": "Avengers: Age of Ultron",
  "year": "2015",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 2",
  "genre": "Action / Superhero",
  "rating": 7.3,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
  "cast": ["Robert Downey Jr.", "Chris Hemsworth", "Scarlett Johansson", "Mark Ruffalo", "Elizabeth Olsen"]
}),
m({
  "id": "mcu-ant-man-1",
  "title": "Ant-Man",
  "year": "2015",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 2",
  "genre": "Action / Comedy",
  "rating": 7.3,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
  "cast": ["Paul Rudd", "Evangeline Lilly", "Michael Douglas", "Corey Stoll"]
}),
// (Continue for every MCU movie…)
m({
  "id": "mcu-civil-war",
  "title": "Captain America: Civil War",
  "year": "2016",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Superhero",
  "rating": 7.8,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
  "cast": ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson", "Sebastian Stan", "Anthony Mackie"]
}),
m({
  "id": "mcu-doctor-strange-1",
  "title": "Doctor Strange",
  "year": "2016",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Fantasy / Superhero",
  "rating": 7.5,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg",
  "cast": ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Rachel McAdams", "Tilda Swinton"]
}),
m({
  "id": "mcu-gotg-2",
  "title": "Guardians of the Galaxy Vol. 2",
  "year": "2017",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Sci-Fi / Comedy",
  "rating": 7.6,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
  "cast": ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Bradley Cooper", "Kurt Russell"]
}),
m({
  "id": "mcu-spidey-homecoming",
  "title": "Spider-Man: Homecoming",
  "year": "2017",
  "universe": "Sony",
  "category": "movie",
  "franchise": "MCU / Sony Spider-Man",
  "genre": "Action / Superhero",
  "rating": 7.4,
  "streaming": ["Disney+", "VOD"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
  "cast": ["Tom Holland", "Michael Keaton", "Robert Downey Jr.", "Zendaya", "Marisa Tomei"]
}),
m({
  "id": "mcu-thor-ragnarok",
  "title": "Thor: Ragnarok",
  "year": "2017",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Comedy",
  "rating": 7.9,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
  "cast": ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett", "Mark Ruffalo", "Tessa Thompson"]
}),
m({
  "id": "mcu-black-panther-1",
  "title": "Black Panther",
  "year": "2018",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Superhero",
  "rating": 7.3,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  "cast": ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira", "Letitia Wright"]
}),
m({
  "id": "mcu-infinity-war",
  "title": "Avengers: Infinity War",
  "year": "2018",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Superhero",
  "rating": 8.4,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  "cast": ["Robert Downey Jr.", "Chris Hemsworth", "Chris Evans", "Mark Ruffalo", "Josh Brolin"]
}),
m({
  "id": "mcu-antman-wasp-1",
  "title": "Ant-Man and the Wasp",
  "year": "2018",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Comedy",
  "rating": 7.0,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cFQEO687n1K6umXbInzocxcnAQz.jpg",
  "cast": ["Paul Rudd", "Evangeline Lilly", "Michael Douglas", "Hannah John-Kamen"]
}),
m({
  "id": "mcu-captain-marvel",
  "title": "Captain Marvel",
  "year": "2019",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Sci-Fi",
  "rating": 6.8,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
  "cast": ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "Jude Law"]
}),
m({
  "id": "mcu-endgame",
  "title": "Avengers: Endgame",
  "year": "2019",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 3",
  "genre": "Action / Superhero",
  "rating": 8.4,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  "cast": ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo", "Scarlett Johansson"]
}),
m({
  "id": "mcu-black-widow",
  "title": "Black Widow",
  "year": "2021",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 4",
  "genre": "Action / Spy",
  "rating": 6.7,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
  "cast": ["Scarlett Johansson", "Florence Pugh", "David Harbour", "Rachel Weisz"]
}),
m({
  "id": "mcu-shang-chi",
  "title": "Shang-Chi and the Legend of the Ten Rings",
  "year": "2021",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 4",
  "genre": "Action / Fantasy",
  "rating": 7.4,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/d08HqqeBQSwN8i8MEvpsZ8Cb438.jpg",
  "cast": ["Simu Liu", "Awkwafina", "Meng'er Zhang", "Tony Leung"]
}),
m({
  "id": "mcu-eternals",
  "title": "Eternals",
  "year": "2021",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 4",
  "genre": "Action / Fantasy",
  "rating": 6.3,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
  "cast": ["Gemma Chan", "Richard Madden", "Angelina Jolie", "Salma Hayek", "Kumail Nanjiani"]
}),
m({
  "id": "mcu-spidey-nwh",
  "title": "Spider-Man: No Way Home",
  "year": "2021",
  "universe": "Sony",
  "category": "movie",
  "franchise": "MCU / Sony Spider-Man",
  "genre": "Action / Multiverse",
  "rating": 8.3,
  "streaming": ["VOD"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
  "cast": ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon", "Willem Dafoe"]
}),
m({
  "id": "mcu-drstrange-mom",
  "title": "Doctor Strange in the Multiverse of Madness",
  "year": "2022",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 4",
  "genre": "Horror / Superhero",
  "rating": 7.0,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
  "cast": ["Benedict Cumberbatch", "Elizabeth Olsen", "Chiwetel Ejiofor", "Xochitl Gomez"]
}),
m({
  "id": "mcu-thor-love-thunder",
  "title": "Thor: Love and Thunder",
  "year": "2022",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 4",
  "genre": "Action / Comedy",
  "rating": 6.2,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
  "cast": ["Chris Hemsworth", "Natalie Portman", "Christian Bale", "Tessa Thompson"]
}),
m({
  "id": "mcu-black-panther-2",
  "title": "Black Panther: Wakanda Forever",
  "year": "2022",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 4",
  "genre": "Action / Drama",
  "rating": 7.2,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
  "cast": ["Letitia Wright", "Tenoch Huerta", "Angela Bassett", "Danai Gurira"]
}),
m({
  "id": "mcu-antman-quantumania",
  "title": "Ant-Man and the Wasp: Quantumania",
  "year": "2023",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 5",
  "genre": "Sci-Fi / Superhero",
  "rating": 6.2,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
  "cast": ["Paul Rudd", "Evangeline Lilly", "Kathryn Newton", "Jonathan Majors"]
}),
m({
  "id": "mcu-gotg-3",
  "title": "Guardians of the Galaxy Vol. 3",
  "year": "2023",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 5",
  "genre": "Sci-Fi / Adventure",
  "rating": 8.0,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
  "cast": ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Pom Klementieff", "Karen Gillan"]
}),
m({
  "id": "mcu-marvels",
  "title": "The Marvels",
  "year": "2023",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 5",
  "genre": "Action / Sci-Fi",
  "rating": 6.1,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
  "cast": ["Brie Larson", "Iman Vellani", "Teyonah Parris", "Samuel L. Jackson"]
}),
m({
  "id": "mcu-deadpool-wolverine",
  "title": "Deadpool & Wolverine",
  "year": "2024",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Multiverse Saga",
  "genre": "Action / Comedy",
  "rating": 8.3,
  "streaming": ["VOD"],
  "notes": "Use as the new multiverse crossover anchor.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
  "cast": ["Ryan Reynolds", "Hugh Jackman", "Morena Baccarin", "Emma Corrin"]
}),
m({
  "id": "mcu-cap-brave-new-world",
  "title": "Captain America: Brave New World",
  "year": "2025",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 5",
  "genre": "Action / Superhero",
  "rating": 6.0,
  "notes": "Upcoming – details TBA.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
  "cast": []
}),
m({
  "id": "mcu-thunderbolts",
  "title": "Thunderbolts*",
  "year": "2025",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 5",
  "genre": "Action / Team-up",
  "rating": 7.1,
  "notes": "Anti-hero ensemble movie.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
  "cast": []
}),
m({
  "id": "mcu-fantastic-four-first-steps",
  "title": "The Fantastic 4: First Steps",
  "year": "2025",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Phase 6",
  "genre": "Action / Superhero",
  "rating": 7.0,
  "notes": "Reboot of Marvel’s First Family in the MCU.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/pZPJsaFKWheTOerVhLnpP8TPp4B.jpg",
  "cast": []
}),
// SONY / SPIDER-VERSE / "VENOM":
m({
  "id": "sony-venom-1",
  "title": "Venom",
  "year": "2018",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Sony Spider-Man Universe",
  "genre": "Action / Sci-Fi",
  "rating": 6.6,
  "streaming": ["Netflix / VOD"],
  "poster": "https://image.tmdb.org/t/p/w500/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
  "cast": ["Tom Hardy", "Michelle Williams", "Riz Ahmed", "Scott Haze"]
}),
m({
  "id": "sony-venom-2",
  "title": "Venom: Let There Be Carnage",
  "year": "2021",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Sony Spider-Man Universe",
  "genre": "Action / Sci-Fi",
  "rating": 5.9,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/w500/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
  "cast": ["Tom Hardy", "Woody Harrelson", "Michelle Williams", "Naomie Harris"]
}),
m({
  "id": "sony-venom-3",
  "title": "Venom: The Last Dance",
  "year": "2024",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Sony Spider-Man Universe",
  "genre": "Action / Sci-Fi",
  "rating": 6.0,
  "notes": "Third Venom film – add details once released.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
  "cast": ["Tom Hardy", "Chiwetel Ejiofor", "Juno Temple", "Rhys Ifans"]
}),
m({
  "id": "sony-morbius",
  "title": "Morbius",
  "year": "2022",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Sony Spider-Man Universe",
  "genre": "Action / Horror",
  "rating": 5.2,
  "poster": "https://image.tmdb.org/t/p/w500/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
  "cast": ["Jared Leto", "Matt Smith", "Adria Arjona", "Jared Harris"]
}),
m({
  "id": "sony-madame-web",
  "title": "Madame Web",
  "year": "2024",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Sony Spider-Man Universe",
  "genre": "Action / Superhero",
  "rating": 4.1,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
  "cast": ["Dakota Johnson", "Sydney Sweeney", "Isabela Merced", "Tahar Rahim"]
}),
m({
  "id": "sony-kraven",
  "title": "Kraven the Hunter",
  "year": "2024",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Sony Spider-Man Universe",
  "genre": "Action / Superhero",
  "rating": 4.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
  "cast": ["Aaron Taylor-Johnson", "Russell Crowe", "Ariana DeBose", "Fred Hechinger"]
}),
m({
  "id": "sony-spider-verse-1",
  "title": "Spider-Man: Into the Spider-Verse",
  "year": "2018",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Spider-Verse",
  "genre": "Animation / Superhero",
  "rating": 8.4,
  "streaming": ["Netflix / VOD"],
  "poster": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
  "cast": ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali", "Brian Tyree Henry"]
}),
m({
  "id": "sony-spider-verse-2",
  "title": "Spider-Man: Across the Spider-Verse",
  "year": "2023",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Spider-Verse",
  "genre": "Animation / Superhero",
  "rating": 8.6,
  "streaming": ["Netflix / VOD"],
  "poster": "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
  "cast": ["Shameik Moore", "Hailee Steinfeld", "Brian Tyree Henry", "Oscar Isaac"]
}),
m({
  "id": "sony-your-friendly-neighborhood",
  "title": "Your Friendly Neighborhood Spider-Man",
  "year": "2024",
  "universe": "Sony",
  "category": "series",
  "franchise": "Animated Spider-Man",
  "genre": "Animation / Superhero",
  "rating": 7.2,
  "notes": "Animated series focused on a young Peter Parker.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/kjcsNeqF52YUQ2rUBGLMHwLkxvR.jpg",
  "cast": []
}),
// TOBEY MAGUIRE (Classic)
m({
  "id": "spidey-2002",
  "title": "Spider-Man",
  "year": "2002",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Tobey Maguire Trilogy",
  "genre": "Action / Superhero",
  "rating": 7.4,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg",
  "cast": ["Tobey Maguire", "Kirsten Dunst", "Willem Dafoe", "James Franco"]
}),
m({
  "id": "spidey-2004",
  "title": "Spider-Man 2",
  "year": "2004",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Tobey Maguire Trilogy",
  "genre": "Action / Superhero",
  "rating": 8.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/aGuvNAaaZuWXYQQ6N2v7DeuP6mB.jpg",
  "cast": ["Tobey Maguire", "Kirsten Dunst", "Alfred Molina", "James Franco"]
}),
m({
  "id": "spidey-2007",
  "title": "Spider-Man 3",
  "year": "2007",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Tobey Maguire Trilogy",
  "genre": "Action / Superhero",
  "rating": 6.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg",
  "cast": ["Tobey Maguire", "Kirsten Dunst", "Topher Grace", "Thomas Haden Church"]
}),
// ANDREW GARFIELD (Amazing Spider-Man)
m({
  "id": "tasm-1",
  "title": "The Amazing Spider-Man",
  "year": "2012",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Andrew Garfield Duology",
  "genre": "Action / Superhero",
  "rating": 6.9,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
  "cast": ["Andrew Garfield", "Emma Stone", "Rhys Ifans", "Denis Leary"]
}),
m({
  "id": "tasm-2",
  "title": "The Amazing Spider-Man 2",
  "year": "2014",
  "universe": "Sony",
  "category": "movie",
  "franchise": "Andrew Garfield Duology",
  "genre": "Action / Superhero",
  "rating": 6.5,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dGjoPttcbKR5VWg1jQuNFB247KL.jpg",
  "cast": ["Andrew Garfield", "Emma Stone", "Jamie Foxx", "Dane DeHaan"]
}),
// X-"MEN":
m({
  "id": "xm-2000",
  "title": "X-Men",
  "year": "2000",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "X-Men",
  "genre": "Action / Superhero",
  "rating": 7.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/bRDAc4GogyS9ci3ow7UnInOcriN.jpg",
  "cast": ["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "Famke Janssen", "James Marsden"]
}),
m({
  "id": "xm-x2",
  "title": "X2: X-Men United",
  "year": "2003",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "X-Men",
  "genre": "Action / Superhero",
  "rating": 7.4,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/bWMw0FMsY8DICgrQnrTSWbzEgtr.jpg",
  "cast": ["Hugh Jackman", "Patrick Stewart", "Halle Berry", "Ian McKellen", "Famke Janssen"]
}),
m({
  "id": "xm-last-stand",
  "title": "X-Men: The Last Stand",
  "year": "2006",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "X-Men Trilogy",
  "genre": "Action / Superhero",
  "rating": 6.6,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/a2xicU8DpKtRizOHjQLC1JyCSRS.jpg",
  "cast": ["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "Famke Janssen", "Halle Berry"]
}),
m({
  "id": "xm-origins-wolverine",
  "title": "X-Men Origins- Wolverine",
  "year": "2009",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "Wolverine",
  "genre": "Action / Superhero",
  "rating": 6.5,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/yj8LbTju1p7CUJg7US2unSBk33s.jpg",
  "cast": ["Hugh Jackman", "Liev Schreiber", "Ryan Reynolds", "Danny Huston"]
}),
m({
  "id": "xm-first-class",
  "title": "X-Men: First Class",
  "year": "2011",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "First Class Era",
  "genre": "Action / Superhero",
  "rating": 7.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hNEokmUke0dazoBhttFN0o3L7Xv.jpg",
  "cast": ["James McAvoy", "Michael Fassbender", "Jennifer Lawrence", "Kevin Bacon"]
}),
m({
  "id": "xm-the-wolverine",
  "title": "The Wolverine",
  "year": "2013",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "Wolverine",
  "genre": "Action / Superhero",
  "rating": 6.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/t2wVAcoRlKvEIVSbiYDb8d0QqqS.jpg",
  "cast": ["Hugh Jackman", "Tao Okamoto", "Rila Fukushima", "Svetlana Khodchenkova"]
}),
m({
  "id": "xm-dofp",
  "title": "X-Men: Days of Future Past",
  "year": "2014",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "First Class Era",
  "genre": "Action / Time-travel",
  "rating": 7.9,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
  "cast": ["Hugh Jackman", "James McAvoy", "Michael Fassbender", "Jennifer Lawrence", "Patrick Stewart"]
}),
m({
  "id": "xm-apocalypse",
  "title": "X-Men: Apocalypse",
  "year": "2016",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "First Class Era",
  "genre": "Action / Superhero",
  "rating": 6.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ikA8UhYdTGpqbatFa93nIf6noSr.jpg",
  "cast": ["James McAvoy", "Oscar Isaac", "Michael Fassbender", "Jennifer Lawrence", "Sophie Turner"]
}),
m({
  "id": "xm-logan",
  "title": "Logan",
  "year": "2017",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "Wolverine",
  "genre": "Drama / Superhero",
  "rating": 8.1,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
  "cast": ["Hugh Jackman", "Patrick Stewart", "Dafne Keen", "Boyd Holbrook"]
}),
m({
  "id": "xm-dark-phoenix",
  "title": "X-Men: Dark Phoenix",
  "year": "2019",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "First Class Era",
  "genre": "Action / Superhero",
  "rating": 5.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
  "cast": ["Sophie Turner", "James McAvoy", "Michael Fassbender", "Jennifer Lawrence"]
}),
m({
  "id": "xm-new-mutants",
  "title": "The New Mutants",
  "year": "2020",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "X-Verse",
  "genre": "Horror / Superhero",
  "rating": 5.3,
  "poster": "https://image.tmdb.org/t/p/w500/xZNw9xxtwbEf25NYoz52KdbXHPM.jpg",
  "cast": ["Maisie Williams", "Anya Taylor-Joy", "Charlie Heaton", "Blu Hunt"]
}),
m({
  "id": "deadpool-1",
  "title": "Deadpool",
  "year": "2016",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "Deadpool",
  "genre": "Action / Comedy",
  "rating": 8.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
  "cast": ["Ryan Reynolds", "Morena Baccarin", "Ed Skrein", "T.J. Miller"]
}),
m({
  "id": "deadpool-2",
  "title": "Deadpool 2",
  "year": "2018",
  "universe": "X-Men",
  "category": "movie",
  "franchise": "Deadpool",
  "genre": "Action / Comedy",
  "rating": 7.6,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
  "cast": ["Ryan Reynolds", "Josh Brolin", "Morena Baccarin", "Julian Dennison"]
}),
// DCEU & NOLAN "BATMAN":
m({
  "id": "dceu-suicide-squad-2",
  "title": "The Suicide Squad",
  "year": "2021",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Comedy",
  "rating": 7.0,
  "streaming": ["VOD"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/q61qEyssk2ku3okWICKArlAdhBn.jpg",
  "cast": ["Margot Robbie", "Idris Elba", "John Cena", "Joel Kinnaman"]
}),
m({
  "id": "dceu-black-adam-1",
  "title": "Black Adam",
  "year": "2022",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Fantasy",
  "rating": 6.1,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
  "cast": ["Dwayne Johnson", "Aldis Hodge", "Pierce Brosnan", "Noah Centineo"]
}),
m({
  "id": "dceu-shazam-2",
  "title": "Shazam! Fury of the Gods",
  "year": "2023",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Comedy",
  "rating": 5.9,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
  "cast": ["Zachary Levi", "Asher Angel", "Jack Dylan Grazer", "Helen Mirren"]
}),
m({
  "id": "dceu-flash-1",
  "title": "The Flash",
  "year": "2023",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Adventure",
  "rating": 6.6,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
  "cast": ["Ezra Miller", "Michael Keaton", "Sasha Calle", "Michael Shannon"]
}),
m({
  "id": "dceu-blue-beetle-1",
  "title": "Blue Beetle",
  "year": "2023",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Sci-Fi",
  "rating": 5.9,
  "streaming": ["VOD"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
  "cast": ["Xolo Maridueña", "Bruna Marquezine", "George Lopez", "Susan Sarandon"]
}),
m({
  "id": "dceu-aquaman-2",
  "title": "Aquaman and the Lost Kingdom",
  "year": "2023",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Adventure",
  "rating": 5.6,
  "streaming": ["VOD"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
  "cast": ["Jason Momoa", "Patrick Wilson", "Yahya Abdul-Mateen II", "Amber Heard"]
}),
m({
  "id": "batman-begins-1",
  "title": "Batman Begins",
  "year": "2005",
  "universe": "DC",
  "category": "movie",
  "franchise": "The Dark Knight Trilogy",
  "genre": "Action / Crime",
  "rating": 8.2,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg",
  "cast": ["Christian Bale", "Michael Caine", "Liam Neeson", "Katie Holmes"]
}),
m({
  "id": "dark-knight-1",
  "title": "The Dark Knight",
  "year": "2008",
  "universe": "DC",
  "category": "movie",
  "franchise": "The Dark Knight Trilogy",
  "genre": "Action / Crime",
  "rating": 9.0,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"]
}),
m({
  "id": "dark-knight-rises-1",
  "title": "The Dark Knight Rises",
  "year": "2012",
  "universe": "DC",
  "category": "movie",
  "franchise": "The Dark Knight Trilogy",
  "genre": "Action / Crime",
  "rating": 8.4,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
  "cast": ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"]
}),
m({
  "id": "dceu-man-of-steel",
  "title": "Man of Steel",
  "year": "2013",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 7.1,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/dksTL9NXc3GqPBRHYHcy1aIwjS.jpg",
  "cast": ["Henry Cavill", "Amy Adams", "Michael Shannon", "Russell Crowe"]
}),
m({
  "id": "dceu-bvs",
  "title": "Batman v Superman: Dawn of Justice",
  "year": "2016",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 6.4,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
  "cast": ["Ben Affleck", "Henry Cavill", "Gal Gadot", "Jesse Eisenberg"]
}),
m({
  "id": "dceu-suicide-squad",
  "title": "Suicide Squad",
  "year": "2016",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 5.9,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/xFw9RXKZDvevAGocgBK0zteto4U.jpg",
  "cast": ["Will Smith", "Margot Robbie", "Jared Leto", "Viola Davis"]
}),
m({
  "id": "dceu-wonder-woman-1",
  "title": "Wonder Woman",
  "year": "2017",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 7.3,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg",
  "cast": ["Gal Gadot", "Chris Pine", "Robin Wright", "Danny Huston"]
}),
m({
  "id": "dceu-justice-league",
  "title": "Justice League",
  "year": "2017",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 6.0,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
  "cast": ["Ben Affleck", "Henry Cavill", "Gal Gadot", "Jason Momoa", "Ezra Miller"]
}),
m({
  "id": "dceu-aquaman-1",
  "title": "Aquaman",
  "year": "2018",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 6.8,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/xLPffWMhMj1l50ND3KchMjYoKmE.jpg",
  "cast": ["Jason Momoa", "Amber Heard", "Willem Dafoe", "Patrick Wilson"]
}),
m({
  "id": "dceu-shazam-1",
  "title": "Shazam!",
  "year": "2019",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Comedy",
  "rating": 7.0,
  "streaming": ["VOD"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
  "cast": ["Zachary Levi", "Mark Strong", "Asher Angel", "Jack Dylan Grazer"]
}),
m({
  "id": "dceu-birds-of-prey",
  "title": "Birds of Prey: And the Fantabulous Emancipation of One Harley Quinn",
  "year": "2020",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Comedy",
  "rating": 6.1,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
  "cast": ["Margot Robbie", "Mary Elizabeth Winstead", "Jurnee Smollett", "Ewan McGregor"]
}),
m({
  "id": "dceu-ww84",
  "title": "Wonder Woman 1984",
  "year": "2020",
  "universe": "DC",
  "category": "movie",
  "franchise": "DCEU",
  "genre": "Action / Superhero",
  "rating": 5.3,
  "streaming": ["VOD"],
  "poster": "https://image.tmdb.org/t/p/original/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
  "cast": ["Gal Gadot", "Chris Pine", "Kristen Wiig", "Pedro Pascal"]
}),
m({
  "id": "blade-1",
  "title": "Blade",
  "year": "1998",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Blade Trilogy",
  "genre": "Action / Horror",
  "rating": 7.1,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hx0sdduAsr4rq03RZKZzglR25z7.jpg",
  "cast": ["Wesley Snipes", "Stephen Dorff", "Kris Kristofferson", "N'Bushe Wright"]
}),
m({
  "id": "blade-2",
  "title": "Blade II",
  "year": "2002",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Blade Trilogy",
  "genre": "Action / Horror",
  "rating": 6.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/azzTa03g0Fb8HC7O3521qq0oc8Q.jpg",
  "cast": ["Wesley Snipes", "Kris Kristofferson", "Ron Perlman", "Leonor Varela"]
}),
m({
  "id": "blade-3",
  "title": "Blade: Trinity",
  "year": "2004",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Blade Trilogy",
  "genre": "Action / Horror",
  "rating": 5.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/r6ycjrStmmAqiY1oDjAli9NArCa.jpg",
  "cast": ["Wesley Snipes", "Jessica Biel", "Ryan Reynolds", "Kris Kristofferson"]
}),
m({
  "id": "howard-duck",
  "title": "Howard the Duck",
  "year": "1986",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Legacy Marvel",
  "genre": "Comedy / Sci-Fi",
  "rating": 4.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/eU0dWo8PJgsSAZFbcyHiUpuLSyW.jpg",
  "cast": ["Lea Thompson", "Jeffrey Jones", "Tim Robbins", "Ed Gale"]
}),
m({
  "id": "punisher-2004",
  "title": "The Punisher",
  "year": "2004",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Legacy Marvel",
  "genre": "Action / Crime",
  "rating": 6.4,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/7rmA1HwYp2GKM85BL0cVwCaosGr.jpg",
  "cast": ["Thomas Jane", "John Travolta", "Will Patton", "Roy Scheider"]
}),
m({
  "id": "punisher-war-zone",
  "title": "Punisher: War Zone",
  "year": "2008",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Legacy Marvel",
  "genre": "Action / Crime",
  "rating": 5.9,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/oOvKJgYUIpfswGHAdW6159bPbvM.jpg",
  "cast": ["Ray Stevenson", "Dominic West", "Julie Benz", "Wayne Knight"]
}),
m({
  "id": "fantastic-four-2005",
  "title": "Fantastic Four",
  "year": "2005",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Fox Fantastic Four",
  "genre": "Action / Superhero",
  "rating": 5.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5qLP3JVg8NE3zdZd48lqhx7iN5Q.jpg",
  "cast": ["Ioan Gruffudd", "Jessica Alba", "Chris Evans", "Michael Chiklis"]
}),
m({
  "id": "fantastic-four-2007",
  "title": "Fantastic Four: Rise of the Silver Surfer",
  "year": "2007",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Fox Fantastic Four",
  "genre": "Action / Superhero",
  "rating": 5.6,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/1rxTraSO45jbvTrCeSvJ6RmOu1b.jpg",
  "cast": ["Ioan Gruffudd", "Jessica Alba", "Chris Evans", "Michael Chiklis", "Doug Jones"]
}),
m({
  "id": "fantastic-four-2015",
  "title": "Fantastic Four (2015)",
  "year": "2015",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Fox Fantastic Four Reboot",
  "genre": "Action / Superhero",
  "rating": 4.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cDroz5qSlP8xZ6tOpeYoPkBvKyL.jpg",
  "cast": ["Miles Teller", "Michael B. Jordan", "Kate Mara", "Jamie Bell"]
}),
m({
  "id": "ghost-rider-1",
  "title": "Ghost Rider",
  "year": "2007",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Ghost Rider",
  "genre": "Action / Horror",
  "rating": 5.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/1pyU94dAY7npDQCKuxCSyX9KthN.jpg",
  "cast": ["Nicolas Cage", "Eva Mendes", "Sam Elliott", "Wes Bentley"]
}),
m({
  "id": "ghost-rider-2",
  "title": "Ghost Rider: Spirit of Vengeance",
  "year": "2011",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Ghost Rider",
  "genre": "Action / Horror",
  "rating": 4.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fUJOWsjjE8u1r4YOLYe1RLYy7bm.jpg",
  "cast": ["Nicolas Cage", "Violante Placido", "Ciarán Hinds", "Idris Elba"]
}),
m({
  "id": "daredevil-2003-movie",
  "title": "Daredevil",
  "year": "2003",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Legacy Marvel",
  "genre": "Action / Superhero",
  "rating": 5.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/oCDBwSkntYamuw8VJIxMRCtDBmi.jpg",
  "cast": ["Ben Affleck", "Jennifer Garner", "Colin Farrell", "Michael Clarke Duncan"]
}),
m({
  "id": "daredevil-born-again",
  "title": "Daredevil: Born Again",
  "year": "2025",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Action / Superhero",
  "rating": 8.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/9lLuhV703HGCbnz6FxnqCwIwzAZ.jpg",
  "cast": ["Charlie Cox", "Vincent D'Onofrio", "Deborah Ann Woll", "Elden Henson"]
}),
m({
  "id": "elektra-2005",
  "title": "Elektra",
  "year": "2005",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "Legacy Marvel",
  "genre": "Action / Superhero",
  "rating": 4.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gC6s6NKHneSrOKyQZnUMb443RKU.jpg",
  "cast": ["Jennifer Garner", "Goran Visnjic", "Will Yun Lee", "Terence Stamp"]
}),
// MCU DISNEY+ "SERIES":
m({
  "id": "mcu-wandavision",
  "title": "WandaVision",
  "year": "2021",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Sitcom / Superhero",
  "rating": 8.0,
  "streaming": ["Disney+"],
  "notes": "Limited series – 1 season.",
  "poster": "https://image.tmdb.org/t/p/w500/glKDfE6btIRcVB5zrjspRIs4r52.jpg",
  "cast": ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn", "Teyonah Parris"]
}),
m({
  "id": "mcu-falcon-ws",
  "title": "The Falcon and the Winter Soldier",
  "year": "2021",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Action / Spy",
  "rating": 7.2,
  "streaming": ["Disney+"],
  "poster": "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
  "cast": ["Anthony Mackie", "Sebastian Stan", "Daniel Brühl", "Emily VanCamp"]
}),
m({
  "id": "mcu-loki",
  "title": "Loki",
  "year": "2021",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Sci-Fi / Superhero",
  "rating": 8.2,
  "streaming": ["Disney+"],
  "notes": "Two seasons (2021, 2023).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/oJdVHUYrjdS2IqiNztVIP4GPB1p.jpg",
  "cast": ["Tom Hiddleston", "Sophia Di Martino", "Owen Wilson", "Gugu Mbatha-Raw"]
}),
m({
  "id": "mcu-what-if",
  "title": "What If...?",
  "year": "2021",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Animated",
  "genre": "Animation / Anthology",
  "rating": 7.3,
  "streaming": ["Disney+"],
  "notes": "Alt-universe anthology. Multiple seasons.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
  "cast": ["Jeffrey Wright", "Hayley Atwell", "Lake Bell", "Chadwick Boseman (voice)"]
}),
m({
  "id": "mcu-hawkeye",
  "title": "Hawkeye",
  "year": "2021",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Action / Christmas",
  "rating": 7.4,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
  "cast": ["Jeremy Renner", "Hailee Steinfeld", "Tony Dalton", "Vera Farmiga"]
}),
m({
  "id": "mcu-moon-knight",
  "title": "Moon Knight",
  "year": "2022",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Action / Mystery",
  "rating": 7.3,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vKDUmKO6F9bSKKyHhg7YGbgcEeF.jpg",
  "cast": ["Oscar Isaac", "May Calamawy", "Ethan Hawke", "F. Murray Abraham"]
}),
m({
  "id": "mcu-ms-marvel",
  "title": "Ms. Marvel",
  "year": "2022",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Coming-of-age / Superhero",
  "rating": 6.2,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/3HWWh92kZbD7odwJX7nKmXNZsYo.jpg",
  "cast": ["Iman Vellani", "Matt Lintz", "Yasmeen Fletcher", "Zenobia Shroff"]
}),
m({
  "id": "mcu-she-hulk",
  "title": "She-Hulk: Attorney at Law",
  "year": "2022",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Legal Comedy / Superhero",
  "rating": 5.3,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg",
  "cast": ["Tatiana Maslany", "Ginger Gonzaga", "Jameela Jamil", "Mark Ruffalo"]
}),
m({
  "id": "mcu-i-am-groot",
  "title": "I Am Groot",
  "year": "2022",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Shorts",
  "genre": "Animation / Shorts",
  "rating": 6.7,
  "streaming": ["Disney+"],
  "notes": "Two seasons of shorts.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lYwFSsP4KsoRhOLhJvBFp3GEGEm.jpg",
  "cast": ["Vin Diesel (voice)", "Bradley Cooper (voice)", "James Gunn (voice)"]
}),
m({
  "id": "mcu-werewolf-night",
  "title": "Werewolf by Night",
  "year": "2022",
  "universe": "Marvel",
  "category": "movie",
  "franchise": "MCU – Special Presentation",
  "genre": "Horror / Superhero",
  "rating": 7.1,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
  "cast": ["Gael García Bernal", "Laura Donnelly", "Harriet Sansom Harris"]
}),
m({
  "id": "mcu-secret-invasion",
  "title": "Secret Invasion",
  "year": "2023",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Spy Thriller / Sci-Fi",
  "rating": 5.8,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/f5ZMzzCvt2IzVDxr54gHPv9jlC9.jpg",
  "cast": ["Samuel L. Jackson", "Ben Mendelsohn", "Emilia Clarke", "Kingsley Ben-Adir"]
}),
m({
  "id": "mcu-echo",
  "title": "Echo",
  "year": "2024",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Crime / Superhero",
  "rating": 5.9,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vFyJH630cF68LohVYjQW49074Sy.jpg",
  "cast": ["Alaqua Cox", "Chaske Spencer", "Devery Jacobs", "Zahn McClarnon"]
}),
m({
  "id": "mcu-agatha",
  "title": "Agatha All Along",
  "year": "2024",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Disney+",
  "genre": "Dark Comedy / Supernatural",
  "rating": 7.5,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/mGsxKwXUjojitRv2E9qMTbxbBRd.jpg",
  "cast": ["Kathryn Hahn"]
}),
m({
  "id": "mcu-marvel-zombies",
  "title": "Marvel Zombies",
  "year": "2024",
  "universe": "Marvel",
  "category": "series",
  "franchise": "MCU – Animated",
  "genre": "Horror / Animation",
  "rating": 7.1,
  "streaming": ["Disney+"],
  "notes": "Animated spin-off of the What If...? zombie episode.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/mwKj9ERGFXsWot0nXgQ5yMQf9I7.jpg",
  "cast": []
}),

// NETFLIX / STREET-LEVEL "MARVEL":
m({
  "id": "netflix-daredevil-1-3",
  "title": "Marvel's Daredevil",
  "year": "2015",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Netflix Defenders Saga",
  "genre": "Crime / Superhero",
  "rating": 8.6,
  "streaming": ["Disney+", "Netflix (earlier)"],
  "notes": "Three seasons (2015–2018). Treat as one show in this list.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
  "cast": ["Charlie Cox", "Deborah Ann Woll", "Elden Henson", "Vincent D'Onofrio"]
}),
m({
  "id": "netflix-jessica-jones",
  "title": "Marvel's Jessica Jones",
  "year": "2015",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Netflix Defenders Saga",
  "genre": "Noir / Superhero",
  "rating": 7.8,
  "notes": "Three seasons (2015–2019).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/paf9wL3mOW9LT3ZjRxXqJcjeMEv.jpg",
  "cast": ["Krysten Ritter", "Rachael Taylor", "Wil Traval", "David Tennant"]
}),
m({
  "id": "netflix-luke-cage",
  "title": "Marvel's Luke Cage",
  "year": "2016",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Netflix Defenders Saga",
  "genre": "Crime / Superhero",
  "rating": 7.2,
  "notes": "Two seasons (2016–2018).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6R62oGGufhsf6DiMknCi047N0b7.jpg",
  "cast": ["Mike Colter", "Simone Missick", "Theo Rossi", "Alfre Woodard"]
}),
m({
  "id": "netflix-iron-fist",
  "title": "Marvel's Iron Fist",
  "year": "2017",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Netflix Defenders Saga",
  "genre": "Martial Arts / Superhero",
  "rating": 6.5,
  "notes": "Two seasons (2017–2018).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/4l6KD9HhtD6nCDEfg10Lp6C6zah.jpg",
  "cast": ["Finn Jones", "Jessica Henwick", "Tom Pelphrey", "Sacha Dhawan"]
}),
m({
  "id": "netflix-defenders",
  "title": "Marvel's The Defenders",
  "year": "2017",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Netflix Defenders Saga",
  "genre": "Team-Up / Superhero",
  "rating": 7.4,
  "notes": "8-episode crossover event.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/49XzINhH4LFsgz7cx6TOPcHUJUL.jpg",
  "cast": ["Charlie Cox", "Krysten Ritter", "Mike Colter", "Finn Jones"]
}),
m({
  "id": "netflix-punisher",
  "title": "Marvel's The Punisher",
  "year": "2017",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Netflix Defenders Saga",
  "genre": "Crime / Action",
  "rating": 8.6,
  "notes": "Two seasons (2017–2019).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/tM6xqRKXoloH9UchaJEyyRE9O1w.jpg",
  "cast": ["Jon Bernthal", "Ebon Moss-Bachrach", "Ben Barnes", "Amber Rose Revah"]
}),
// AGENTS OF SHIELD & MARVEL "TV":
m({
  "id": "aos",
  "title": "Marvel's Agents of S.H.I.E.L.D.",
  "year": "2013",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Marvel Television",
  "genre": "Action / Sci-Fi",
  "rating": 7.5,
  "notes": "7 seasons (2013–2020). Use this as one entry instead of every season separately.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
  "cast": ["Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Elizabeth Henstridge", "Iain De Caestecker"]
}),
m({
  "id": "agent-carter",
  "title": "Marvel's Agent Carter",
  "year": "2015",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Marvel Television",
  "genre": "Spy / Period",
  "rating": 7.8,
  "notes": "2 seasons.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fe79VYyLp5ZBstpJ4oukpuUT3B.jpg",
  "cast": ["Hayley Atwell", "James D'Arcy", "Enver Gjokaj", "Chad Michael Murray"]
}),
m({
  "id": "cloak-dagger",
  "title": "Marvel's Cloak & Dagger",
  "year": "2018",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Marvel Television",
  "genre": "YA / Superhero",
  "rating": 6.6,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
  "cast": ["Olivia Holt", "Aubrey Joseph", "Gloria Reuben", "Andrea Roth"]
}),
m({
  "id": "runaways",
  "title": "Marvel's Runaways",
  "year": "2017",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Marvel Television",
  "genre": "YA / Superhero",
  "rating": 6.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/zceMrfO17AQkeWJZNra4O90s1vE.jpg",
  "cast": ["Rhenzy Feliz", "Lyrica Okano", "Virginia Gardner", "Ariela Barer"]
}),
m({
  "id": "helstrom",
  "title": "Helstrom",
  "year": "2020",
  "universe": "Marvel",
  "category": "series",
  "franchise": "Marvel Television",
  "genre": "Horror / Supernatural",
  "rating": 6.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5QmcKsepYpO9XYsWNLwsiULoaAu.jpg",
  "cast": ["Tom Austen", "Sydney Lemmon", "Elizabeth Marvel", "Robert Wisdom"]
}),
// STAR WARS "SERIES":
m({
  "id": "sw-clone-wars",
  "title": "Star Wars: The Clone Wars",
  "year": "2008",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Animated",
  "genre": "Animation / Sci-Fi",
  "rating": 8.5,
  "notes": "Movie + 7-season series.",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/e1nWfnnCVqxS2LeTO3dwGyAsG2V.jpg",
  "cast": ["Matt Lanter", "Ashley Eckstein", "James Arnold Taylor", "Tom Kane"]
}),
m({
  "id": "sw-tales-jedi",
  "title": "Tales of the Jedi",
  "year": "2022",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Animated",
  "genre": "Anthology / Animation",
  "rating": 8.1,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/k3nWQb0E8mLSR8acSkJP78VRVMv.jpg",
  "cast": ["Ashley Eckstein", "Corey Burton", "Liam Neeson", "Janina Gavankar"]
}),
m({
  "id": "sw-rebels",
  "title": "Star Wars Rebels",
  "year": "2014",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Animated",
  "genre": "Animation / Adventure",
  "rating": 8.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/jmgR8330sKEJehr27rQ3bODnrlP.jpg",
  "cast": ["Taylor Gray", "Vanessa Marshall", "Freddie Prinze Jr.", "Steve Blum"]
}),
m({
  "id": "sw-bad-batch",
  "title": "Star Wars: The Bad Batch",
  "year": "2021",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Animated",
  "genre": "Animation / War",
  "rating": 7.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cDQAvfgAqnKuklerrZylZr6PCQa.jpg",
  "cast": ["Dee Bradley Baker", "Michelle Ang", "Noshir Dalal", "Ben Diskin"]
}),
m({
  "id": "sw-mandalorian",
  "title": "The Mandalorian",
  "year": "2019",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Live-Action",
  "genre": "Western / Sci-Fi",
  "rating": 8.6,
  "notes": "3 seasons so far.",
  "poster": "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
  "cast": ["Pedro Pascal", "Carl Weathers", "Gina Carano", "Giancarlo Esposito"]
}),
m({
  "id": "sw-book-boba",
  "title": "The Book of Boba Fett",
  "year": "2021",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Live-Action",
  "genre": "Crime / Sci-Fi",
  "rating": 7.2,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gNbdjDi1HamTCrfvM9JeA94bNi2.jpg",
  "cast": ["Temuera Morrison", "Ming-Na Wen", "Matt Berry", "Jennifer Beals"]
}),
m({
  "id": "sw-obi-wan",
  "title": "Obi-Wan Kenobi",
  "year": "2022",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Live-Action",
  "genre": "Limited Series / Sci-Fi",
  "rating": 7.1,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qJRB789ceLryrLvOKrZqLKr2CGf.jpg",
  "cast": ["Ewan McGregor", "Rupert Friend", "Moses Ingram", "Joel Edgerton"]
}),
m({
  "id": "sw-andor",
  "title": "Andor",
  "year": "2022",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Live-Action",
  "genre": "Spy Thriller / Sci-Fi",
  "rating": 8.5,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/khZqmwHQicTYoS7Flreb9EddFZC.jpg",
  "cast": ["Diego Luna", "Genevieve O'Reilly", "Stellan Skarsgård", "Adria Arjona"]
}),
m({
  "id": "sw-ahsoka",
  "title": "Ahsoka",
  "year": "2023",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Live-Action",
  "genre": "Adventure / Sci-Fi",
  "rating": 7.4,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/eiJeWeCAEZAmRppnXHiTWDcCd3Q.jpg",
  "cast": ["Rosario Dawson", "Natasha Liu Bordizzo", "Mary Elizabeth Winstead", "Ivanna Sakhno"]
}),
m({
  "id": "sw-acolyte",
  "title": "The Acolyte",
  "year": "2024",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "High Republic",
  "genre": "Mystery / Sci-Fi",
  "rating": "",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/1dcoIe9uKbWykq2zsnkaz2rxPnP.jpg",
  "cast": []
}),
m({
  "id": "sw-skeleton-crew",
  "title": "Star Wars: Skeleton Crew",
  "year": "2024",
  "universe": "Star Wars",
  "category": "series",
  "franchise": "Live-Action",
  "genre": "Adventure / Sci-Fi",
  "rating": "",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/srQbJhLRKoAwRrNN5ga7webPHbC.jpg",
  "cast": []
}),
// DC ARROWVERSE "SERIES":
m({
  "id": "dc-arrow",
  "title": "Arrow",
  "year": "2012",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse",
  "genre": "Crime / Superhero",
  "rating": 7.5,
  "notes": "8 seasons (2012–2020).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/u8ZHFj1jC384JEkTt3vNg1DfWEb.jpg",
  "cast": ["Stephen Amell", "David Ramsey", "Emily Bett Rickards", "Katie Cassidy"]
}),
m({
  "id": "dc-flash",
  "title": "The Flash",
  "year": "2014",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse",
  "genre": "Action / Superhero",
  "rating": 7.5,
  "notes": "9 seasons (2014–2023).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/yZevl2vHQgmosfwUdVNzviIfaWS.jpg",
  "cast": ["Grant Gustin", "Candice Patton", "Danielle Panabaker", "Carlos Valdes"]
}),
m({
  "id": "dc-constantine",
  "title": "Constantine",
  "year": "2014",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse Adjacent",
  "genre": "Horror / Supernatural",
  "rating": 7.5,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gQ3bA1DBKyZwkDCHJFEAT0MkKpu.jpg",
  "cast": ["Matt Ryan", "Angélica Celaya", "Charles Halford", "Harold Perrineau"]
}),
m({
  "id": "dc-supergirl",
  "title": "Supergirl",
  "year": "2015",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse",
  "genre": "Action / Superhero",
  "rating": 6.2,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cFO65xb0xiXKqk5BmgHawCXB1i0.jpg",
  "cast": ["Melissa Benoist", "Chyler Leigh", "David Harewood", "Mehcad Brooks"]
}),
m({
  "id": "dc-legends",
  "title": "Legends of Tomorrow",
  "year": "2016",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse",
  "genre": "Time-travel / Superhero",
  "rating": 6.7,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qNgAcg4gNYbZ9mySLB9ZX4ehZb6.jpg",
  "cast": ["Caity Lotz", "Brandon Routh", "Dominic Purcell", "Franz Drameh"]
}),
m({
  "id": "dc-black-lightning",
  "title": "Black Lightning",
  "year": "2018",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse",
  "genre": "Drama / Superhero",
  "rating": 6.1,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/h1xbvvO6oqchfLe6xh0yLNnQxeM.jpg",
  "cast": ["Cress Williams", "China Anne McClain", "Nafessa Williams", "Christine Adams"]
}),
m({
  "id": "dc-batwoman",
  "title": "Batwoman",
  "year": "2019",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse",
  "genre": "Crime / Superhero",
  "rating": 3.6,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/pBpxKiitMuYXvtsXNSzya8DKKzV.jpg",
  "cast": ["Ruby Rose", "Rachel Skarsten", "Camrus Johnson", "Meagan Tandy"]
}),
m({
  "id": "dc-superman-lois",
  "title": "Superman & Lois",
  "year": "2021",
  "universe": "DC",
  "category": "series",
  "franchise": "Arrowverse Adjacent",
  "genre": "Drama / Superhero",
  "rating": 7.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vlv1gn98GqMnKHLSh0dNciqGfBl.jpg",
  "cast": ["Tyler Hoechlin", "Elizabeth Tulloch", "Alex Garfin", "Jordan Elsass"]
}),
// Harry Potter movies
m({
  "id": "hp-1",
  "title": "Harry Potter and the Philosopher's Stone",
  "year": "2001",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 7.6,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-2",
  "title": "Harry Potter and the Chamber of Secrets",
  "year": "2002",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 6.8,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-3",
  "title": "Harry Potter and the Prisoner of Azkaban",
  "year": "2004",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 6.9,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-4",
  "title": "Harry Potter and the Goblet of Fire",
  "year": "2005",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 7.4,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-5",
  "title": "Harry Potter and the Order of the Phoenix",
  "year": "2007",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 7.5,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-6",
  "title": "Harry Potter and the Half-Blood Prince",
  "year": "2009",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 7.4,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-7",
  "title": "Harry Potter and the Deathly Hallows: Part 1",
  "year": "2011",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 7.4,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "hp-8",
  "title": "Harry Potter and the Deathly Hallows: Part 2",
  "year": "2011",
  "universe": "Harry Potter",
  "category": "movie",
  "franchise": "Harry Potter",
  "genre": "Fantasy / Adventure",
  "rating": 7.4,
  "streaming": ["Disney+"],
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/c54HpQmuwXjHq2C9wmoACjxoom3.jpg",
  "cast": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Mark Ruffalo"]
}),
m({
  "id": "twilight-1",
  "title": "Twilight",
  "year": "2008",
  "universe": "Twilight",
  "category": "movie",
  "franchise": "Twilight Saga",
  "genre": "Fantasy / Romance",
  "rating": 5.3,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/3Gkb6jm6962ADUPaCBqzz9CTbn9.jpg",
  "cast": ["Kristen Stewart", "Robert Pattinson", "Taylor Lautner", "Billy Burke"]
}),
m({
  "id": "twilight-2",
  "title": "The Twilight Saga: New Moon",
  "year": "2009",
  "universe": "Twilight",
  "category": "movie",
  "franchise": "Twilight Saga",
  "genre": "Fantasy / Romance",
  "rating": 4.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/k2qTooPlHffgNABNWxeJdGMglPK.jpg",
  "cast": ["Kristen Stewart", "Robert Pattinson", "Taylor Lautner", "Billy Burke"]
}),
m({
  "id": "twilight-3",
  "title": "The Twilight Saga: Eclipse",
  "year": "2010",
  "universe": "Twilight",
  "category": "movie",
  "franchise": "Twilight Saga",
  "genre": "Fantasy / Romance",
  "rating": 5.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dK4Gi1UdMiHzHc7r7CZQG4IQ9Sr.jpg",
  "cast": ["Kristen Stewart", "Robert Pattinson", "Taylor Lautner", "Billy Burke"]
}),
m({
  "id": "twilight-4a",
  "title": "The Twilight Saga: Breaking Dawn – Part 1",
  "year": "2011",
  "universe": "Twilight",
  "category": "movie",
  "franchise": "Twilight Saga",
  "genre": "Fantasy / Romance",
  "rating": 4.9,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qs8LsHKYlVRmJbFUiSUhhRAygwj.jpg",
  "cast": ["Kristen Stewart", "Robert Pattinson", "Taylor Lautner", "Billy Burke"]
}),
m({
  "id": "twilight-4b",
  "title": "The Twilight Saga: Breaking Dawn – Part 2",
  "year": "2012",
  "universe": "Twilight",
  "category": "movie",
  "franchise": "Twilight Saga",
  "genre": "Fantasy / Romance",
  "rating": 5.5,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/7IGdPaKujv0BjI0Zd0m0a4CzEjJ.jpg",
  "cast": ["Kristen Stewart", "Robert Pattinson", "Taylor Lautner", "Billy Burke"]
}),
m({
  "id": "lotr-1",
  "title": "The Lord of the Rings: The Fellowship of the Ring",
  "year": "2001",
  "universe": "Middle-earth",
  "category": "movie",
  "franchise": "Lord of the Rings",
  "genre": "Fantasy / Adventure",
  "rating": 8.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom"]
}),
m({
  "id": "lotr-2",
  "title": "The Lord of the Rings: The Two Towers",
  "year": "2002",
  "universe": "Middle-earth",
  "category": "movie",
  "franchise": "Lord of the Rings",
  "genre": "Fantasy / Adventure",
  "rating": 8.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
  "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom"]
}),
m({
  "id": "lotr-3",
  "title": "The Lord of the Rings: The Return of the King",
  "year": "2003",
  "universe": "Middle-earth",
  "category": "movie",
  "franchise": "Lord of the Rings",
  "genre": "Fantasy / Adventure",
  "rating": 9.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
  "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom"]
}),
m({
  "id": "hobbit-1",
  "title": "The Hobbit: An Unexpected Journey",
  "year": "2012",
  "universe": "Middle-earth",
  "category": "movie",
  "franchise": "The Hobbit",
  "genre": "Fantasy / Adventure",
  "rating": 7.8,
  "poster": "https://image.tmdb.org/t/p/w500/xT98tLqatZPQApyRmlPL12LtiWp.jpg",
  "cast": ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Cate Blanchett"]
}),
m({
  "id": "hobbit-2",
  "title": "The Hobbit: The Desolation of Smaug",
  "year": "2013",
  "universe": "Middle-earth",
  "category": "movie",
  "franchise": "The Hobbit",
  "genre": "Fantasy / Adventure",
  "rating": 7.8,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xQYiXsheRCDBA39DOrmaw1aSpbk.jpg",
  "cast": ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Benedict Cumberbatch"]
}),
m({
  "id": "hobbit-3",
  "title": "The Hobbit: The Battle of the Five Armies",
  "year": "2014",
  "universe": "Middle-earth",
  "category": "movie",
  "franchise": "The Hobbit",
  "genre": "Fantasy / Adventure",
  "rating": 7.4,
  "poster": "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
  "cast": ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Luke Evans"]
}),
m({
  "id": "lotr-rings-power",
  "title": "The Lord of the Rings: The Rings of Power",
  "year": "2022",
  "universe": "Middle-earth",
  "category": "series",
  "franchise": "Rings of Power",
  "genre": "Fantasy / Adventure",
  "rating": 7.0,
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/kf5Hz70tjNAHg4swGDzOr9BfoZ1.jpg",
  "cast": ["Morfydd Clark", "Ismael Cruz Cordova", "Charlie Vickers", "Markella Kavenagh"]
}),
m({
  "id": "big-bang-theory",
  "title": "The Big Bang Theory",
  "year": "2007",
  "universe": "None",
  "category": "series",
  "franchise": "Sitcom",
  "genre": "Comedy",
  "rating": 8.1,
  "streaming": ["Max", "HBO Max"],
  "notes": "12 seasons (2007–2019).",
  "poster": "https://image.tmdb.org/t/p/w500/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
  "cast": ["Johnny Galecki", "Jim Parsons", "Kaley Cuoco", "Simon Helberg"]
}),
m({
  "id": "friends",
  "title": "Friends",
  "year": "1994",
  "universe": "None",
  "category": "series",
  "franchise": "Sitcom",
  "genre": "Comedy / Romance",
  "rating": 8.9,
  "streaming": ["Max", "HBO Max"],
  "notes": "10 seasons (1994–2004).",
  "poster": "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
  "cast": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matthew Perry"]
}),
m({
  "id": "the-office-us",
  "title": "The Office (US)",
  "year": "2005",
  "universe": "None",
  "category": "series",
  "franchise": "Sitcom",
  "genre": "Comedy / Mockumentary",
  "rating": 9.0,
  "streaming": ["Peacock"],
  "notes": "9 seasons (2005–2013).",
  "poster": "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
  "cast": ["Steve Carell", "Rainn Wilson", "John Krasinski", "Jenna Fischer"]
}),
m({
  "id": "two-and-a-half-men",
  "title": "Two and a Half Men",
  "year": "2003",
  "universe": "None",
  "category": "series",
  "franchise": "Sitcom",
  "genre": "Comedy",
  "rating": 7.1,
  "streaming": ["Max", "HBO Max"],
  "notes": "12 seasons (2003–2015).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xgfjxyV3g1S68opzuvG6G87muDp.jpg",
  "cast": ["Charlie Sheen", "Jon Cryer", "Angus T. Jones", "Conchata Ferrell"]
}),
m({
  "id": "two-broke-girls",
  "title": "2 Broke Girls",
  "year": "2011",
  "universe": "None",
  "category": "series",
  "franchise": "Sitcom",
  "genre": "Comedy",
  "rating": 6.6,
  "streaming": ["Max", "HBO Max", "Prime Video"],
  "notes": "6 seasons (2011–2017).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/wW1SDEoZ6pDfnSkVQuXwOo8ICep.jpg",
  "cast": ["Kat Dennings", "Beth Behrs", "Garrett Morris", "Jonathan Kite"]
}),
m({
  "id": "himym",
  "title": "How I Met Your Mother",
  "year": "2005",
  "universe": "None",
  "category": "series",
  "franchise": "Sitcom",
  "genre": "Comedy / Romance",
  "rating": 8.3,
  "streaming": ["Hulu", "Disney+"],
  "notes": "9 seasons (2005–2014).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/AltVeoVIn9FQVDpVBvsExYDpLeJ.jpg",
  "cast": ["Josh Radnor", "Jason Segel", "Cobie Smulders", "Neil Patrick Harris"]
}),
m({
  "id": "stranger-things",
  "title": "Stranger Things",
  "year": "2016",
  "universe": "None",
  "category": "series",
  "franchise": "Stranger Things",
  "genre": "Sci-Fi / Thriller",
  "rating": 8.7,
  "streaming": ["Netflix"],
  "notes": "4 seasons (2016–2024, ongoing).",
  "poster": "https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
  "cast": ["Millie Bobby Brown", "Finn Wolfhard", "David Harbour", "Winona Ryder"]
}),
m({
  "id": "locke-and-key",
  "title": "Locke & Key",
  "year": "2020",
  "universe": "None",
  "category": "series",
  "franchise": "Fantasy",
  "genre": "Drama / Fantasy / Horror",
  "rating": 7.3,
  "streaming": ["Netflix"],
  "notes": "3 seasons (2020–2022).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/zuxGfRKziGHPogipnEXXykdDmyT.jpg",
  "cast": ["Darby Stanchfield", "Connor Jessup", "Emilia Jones", "Jackson Robert Scott"]
}),
m({
  "id": "the-boys",
  "title": "The Boys",
  "year": "2019",
  "universe": "None",
  "category": "series",
  "franchise": "The Boys",
  "genre": "Action / Satire / Superhero",
  "rating": 8.7,
  "streaming": ["Prime Video"],
  "notes": "4 seasons (2019–2025, ongoing).",
  "poster": "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
  "cast": ["Karl Urban", "Jack Quaid", "Antony Starr", "Erin Moriarty"]
}),
m({
  "id": "invincible",
  "title": "Invincible",
  "year": "2021",
  "universe": "None",
  "category": "series",
  "franchise": "Invincible",
  "genre": "Animation / Superhero",
  "rating": 8.7,
  "streaming": ["Prime Video"],
  "notes": "2 seasons (2021–2024, ongoing).",
  "poster": "https://image.tmdb.org/t/p/w500/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg",
  "cast": ["Steven Yeun", "J.K. Simmons", "Sandra Oh", "Zazie Beetz"]
}),


m({
  id: "hunger-games-1",
  title: "The Hunger Games",
  year: 2012,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Action",
  rating: 7.2,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
  cast: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
  streaming: ["Peacock Premium", "Prime Video (rental)", "Apple TV"]
}),
m({
  id: "hunger-games-2",
  title: "The Hunger Games: Catching Fire",
  year: 2013,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Action",
  rating: 7.4,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vrQHDXjVmbYzadOXQ0UaObunoy2.jpg",
  cast: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
  streaming: ["Peacock Premium", "Prime Video (rental)", "Apple TV"]
}),
m({
  id: "hunger-games-3",
  title: "The Hunger Games: Mockingjay – Part 1",
  year: 2014,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Action",
  rating: 6.7,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
  cast: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
  streaming: ["Peacock Premium", "Prime Video (rental)", "Apple TV"]
}),
m({
  id: "hunger-games-4",
  title: "The Hunger Games: Mockingjay – Part 2",
  year: 2015,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Action",
  rating: 6.6,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lImKHDfExAulp16grYm8zD5eONE.jpg",
  cast: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
  streaming: ["Peacock Premium", "Prime Video (rental)", "Apple TV"]
}),
m({
  id: "hunger-games-5",
  title: "The Hunger Games: The Ballad of Songbirds and Snakes",
  year: 2023,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Action",
  rating: 7.2,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lrkOYL5GBTFW9cgs9RlojxAcZZF.jpg",
  cast: ["Tom Blyth", "Rachel Zegler", "Peter Dinklage"],
  streaming: ["Peacock Premium", "Prime Video (rental)", "Apple TV"]
}),

m({
  id: "got-series",
  title: "Game of Thrones",
  year: 2011,
  universe: "Other",
  category: "series",
  genre: "Fantasy / Drama",
  rating: 9.2,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
  cast: ["Emilia Clarke", "Kit Harington", "Peter Dinklage", "Lena Headey"],
  streaming: ["Max", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-1",
  title: "Mission: Impossible",
  year: 1996,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.1,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/l5uxY5m5OInWpcExIpKG6AR3rgL.jpg",
  cast: ["Tom Cruise", "Jon Voight", "Emmanuelle Béart"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-2",
  title: "Mission: Impossible II",
  year: 2000,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 6.1,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hfnrual76gPeNFduhD4xzHWpfTw.jpg",
  cast: ["Tom Cruise", "Dougray Scott", "Thandie Newton"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-3",
  title: "Mission: Impossible III",
  year: 2006,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 6.9,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vKGYCpmQyV9uHybWDzXuII8Los5.jpg",
  cast: ["Tom Cruise", "Philip Seymour Hoffman", "Michelle Monaghan"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-4",
  title: "Mission: Impossible – Ghost Protocol",
  year: 2011,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.4,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/eRZTGx7GsiKqPch96k27LK005ZL.jpg",
  cast: ["Tom Cruise", "Jeremy Renner", "Simon Pegg", "Paula Patton"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-5",
  title: "Mission: Impossible – Rogue Nation",
  year: 2015,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.3,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fRJLXQBHK2wyznK5yZbO7vmsuVK.jpg",
  cast: ["Tom Cruise", "Rebecca Ferguson", "Simon Pegg"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-6",
  title: "Mission: Impossible – Fallout",
  year: 2018,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.8,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
  cast: ["Tom Cruise", "Henry Cavill", "Rebecca Ferguson"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "mi-7",
  title: "Mission: Impossible – Dead Reckoning Part One",
  year: 2023,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.6,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
  cast: ["Tom Cruise", "Hayley Atwell", "Rebecca Ferguson"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
({
  id: "mi-8",
  title: "Mission: Impossible – The Final Reckoning",
  year: 2025,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 8.1,
  poster: "https://upload.wikimedia.org/wikipedia/en/1/1f/Mission_Impossible_%E2%80%93_The_Final_Reckoning_Poster.jpg",
  cast: ["Tom Cruise", "Hayley Atwell", "Ving Rhames", "Simon Pegg"],
  streaming: ["Paramount+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "fd-1",
  title: "Final Destination",
  year: 2000,
  universe: "Other",
  category: "movie",
  genre: "Horror / Thriller",
  rating: 6.5,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/1mXhlQMnlfvJ2frxTjZSQNnA9Vp.jpg",
  cast: ["Devon Sawa", "Ali Larter"],
  streaming: ["Prime Video (rental)", "Max"]
}),
m({
  id: "fd-2",
  title: "Final Destination 2",
  year: 2003,
  universe: "Other",
  category: "movie",
  genre: "Horror / Thriller",
  rating: 6.2,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dg6Tf98InieJSClSKQJTQevYWmB.jpg",
  cast: ["A.J. Cook", "Ali Larter"],
  streaming: ["Prime Video (rental)", "Max"]
}),
m({
  id: "fd-3",
  title: "Final Destination 3",
  year: 2006,
  universe: "Other",
  category: "movie",
  genre: "Horror / Thriller",
  rating: 5.8,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/p7ARuNKUGPGvkBiDtIDvAzYzonX.jpg",
  cast: ["Mary Elizabeth Winstead", "Ryan Merriman"],
  streaming: ["Prime Video (rental)", "Max"]
}),
m({
  id: "fd-4",
  title: "The Final Destination",
  year: 2009,
  universe: "Other",
  category: "movie",
  genre: "Horror / Thriller",
  rating: 5.1,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5vxXrr1MqGsT4NNeRITpfDnl4Rq.jpg",
  cast: ["Bobby Campo", "Shantel VanSanten"],
  streaming: ["Prime Video (rental)", "Max"]
}),
m({
  id: "fd-5",
  title: "Final Destination 5",
  year: 2011,
  universe: "Other",
  category: "movie",
  genre: "Horror / Thriller",
  rating: 5.9,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
  cast: ["Nicholas D'Agosto", "Emma Bell"],
  streaming: ["Prime Video (rental)", "Max"]
}),
m({
  id: "hangover-1",
  title: "The Hangover",
  year: 2009,
  universe: "Other",
  category: "movie",
  genre: "Comedy",
  rating: 7.7,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/A0uS9rHR56FeBtpjVki16M5xxSW.jpg",
  cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis"],
  streaming: ["Max", "Prime Video (rental)"]
}),
m({
  id: "hangover-2",
  title: "The Hangover Part II",
  year: 2011,
  universe: "Other",
  category: "movie",
  genre: "Comedy",
  rating: 6.5,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cKZu0Fdkj7dmwbfMpgDqVVCkLJQ.jpg",
  cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis"],
  streaming: ["Max", "Prime Video (rental)"]
}),
m({
  id: "hangover-3",
  title: "The Hangover Part III",
  year: 2013,
  universe: "Other",
  category: "movie",
  genre: "Comedy",
  rating: 5.8,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vtxuPWkdllLNLVyGjKYa267ntuH.jpg",
  cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis"],
  streaming: ["Max", "Prime Video (rental)"]
}),
m({
  id: "bttf-1",
  title: "Back to the Future",
  year: 1985,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Comedy",
  rating: 8.5,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
  cast: ["Michael J. Fox", "Christopher Lloyd"],
  streaming: ["Prime Video (rental)", "Peacock"]
}),
m({
  id: "bttf-2",
  title: "Back to the Future Part II",
  year: 1989,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Comedy",
  rating: 7.8,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/YBawEsTkUZBDajKbd5LiHkmMGf.jpg",
  cast: ["Michael J. Fox", "Christopher Lloyd"],
  streaming: ["Prime Video (rental)", "Peacock"]
}),
m({
  id: "bttf-3",
  title: "Back to the Future Part III",
  year: 1990,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Comedy",
  rating: 7.3,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/crzoVQnMzIrRfHtQw0tLBirNfVg.jpg",
  cast: ["Michael J. Fox", "Christopher Lloyd"],
  streaming: ["Prime Video (rental)", "Peacock"]
}),
m({
  id: "wednesday",
  title: "Wednesday",
  year: 2022,
  universe: "Other",
  category: "series",
  genre: "Comedy / Mystery",
  rating: 8.1,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
  cast: ["Jenna Ortega", "Gwendoline Christie", "Catherine Zeta-Jones"],
  streaming: ["Netflix"]
}),
m({
  id: "breaking-bad",
  title: "Breaking Bad",
  year: 2008,
  universe: "Other",
  category: "series",
  genre: "Crime / Drama",
  rating: 9.5,
  poster:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
  cast:["Bryan Cranston","Aaron Paul"],
  streaming: ["Netflix"]
}),

m({
  id: "avatar-1",
  title: "Avatar",
  year: 2009,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Adventure",
  rating: 7.8,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
  cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
  streaming: ["Disney+", "Prime Video (rental)"]
}),
m({
  id: "avatar-2",
  title: "Avatar: The Way of Water",
  year: 2022,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Adventure",
  rating: 7.6,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
  cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
  streaming: ["Disney+", "Prime Video (rental)"]
}),
// Future planned Avatar sequels (optional placeholders)
m({
  id: "avatar-3",
  title: "Avatar 3",
  year: 2025,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Adventure",
  rating: 0.0,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/g96wHxU7EnoIFwemb2RgohIXrgW.jpg",
  cast: [],
  streaming: []
}),
m({
  id: "tenet",
  title: "Tenet",
  year: 2020,
  universe: "Other",
  category: "movie",
  genre: "Sci-Fi / Action",
  rating: 7.2,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
  cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki"],
  streaming: ["Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-1",
  title: "The Fast and the Furious",
  year: 2001,
  universe: "Other",
  category: "movie",
  genre: "Action / Crime",
  rating: 6.8,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gqY0ITBgT7A82poL9jv851qdnIb.jpg",
  cast: ["Vin Diesel", "Paul Walker", "Michelle Rodriguez", "Jordana Brewster"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-2",
  title: "2 Fast 2 Furious",
  year: 2003,
  universe: "Other",
  category: "movie",
  genre: "Action / Crime",
  rating: 5.9,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6nDZExrDKIXvSAghsFKVFRVJuSf.jpg",
  cast: ["Paul Walker", "Tyrese Gibson", "Eva Mendes", "Ludacris"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-3",
  title: "The Fast and the Furious: Tokyo Drift",
  year: 2006,
  universe: "Other",
  category: "movie",
  genre: "Action / Crime",
  rating: 6.0,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/46xqGOwHbh2TH2avWSw3SMXph4E.jpg",
  cast: ["Lucas Black", "Sung Kang", "Bow Wow"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-4",
  title: "Fast & Furious",
  year: 2009,
  universe: "Other",
  category: "movie",
  genre: "Action / Crime",
  rating: 6.6,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lUtVoRukW7WNtUySwd8hWlByBds.jpg",
  cast: ["Vin Diesel", "Paul Walker", "Michelle Rodriguez", "Jordana Brewster"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-5",
  title: "Fast Five",
  year: 2011,
  universe: "Other",
  category: "movie",
  genre: "Action / Heist",
  rating: 7.3,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gEfQjjQwY7fh5bI4GlG0RrBu7Pz.jpg",
  cast: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Jordana Brewster"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-6",
  title: "Fast & Furious 6",
  year: 2013,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.0,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/thSmnRdrzPBBospIOJjLZBReqzo.jpg",
  cast: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Michelle Rodriguez"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-7",
  title: "Furious 7",
  year: 2015,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 7.1,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg",
  cast: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Michelle Rodriguez"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-8",
  title: "The Fate of the Furious",
  year: 2017,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 6.6,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
  cast: ["Vin Diesel", "Dwayne Johnson", "Michelle Rodriguez", "Charlize Theron"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-9",
  title: "F9",
  year: 2021,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 5.2,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
  cast: ["Vin Diesel", "Michelle Rodriguez", "John Cena", "Tyrese Gibson"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-10",
  title: "Fast X",
  year: 2023,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 5.8,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
  cast: ["Vin Diesel", "Michelle Rodriguez", "Jason Momoa", "Brie Larson"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "f9-hobbs-shaw",
  title: "Fast & Furious Presents: Hobbs & Shaw",
  year: 2019,
  universe: "Other",
  category: "movie",
  genre: "Action / Thriller",
  rating: 6.5,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
  cast: ["Dwayne Johnson", "Jason Statham", "Idris Elba", "Vanessa Kirby"],
  streaming: ["Peacock", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "potc-1",
  title: "Pirates of the Caribbean: The Curse of the Black Pearl",
  year: 2003,
  universe: "Other",
  category: "movie",
  genre: "Adventure / Fantasy",
  rating: 8.1,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/poHwCZeWzJCShH7tOjg8RIoyjcw.jpg",
  cast: ["Johnny Depp", "Geoffrey Rush", "Orlando Bloom", "Keira Knightley"],
  streaming: ["Disney+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "potc-2",
  title: "Pirates of the Caribbean: Dead Man's Chest",
  year: 2006,
  universe: "Other",
  category: "movie",
  genre: "Adventure / Fantasy",
  rating: 7.4,
  poster: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/lAhcKRt0ggTFkeFL95jrGQYaRXs.jpg",
  cast: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Bill Nighy"],
  streaming: ["Disney+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "potc-3",
  title: "Pirates of the Caribbean: At World's End",
  year: 2007,
  universe: "Other",
  category: "movie",
  genre: "Adventure / Fantasy",
  rating: 7.1,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2YMnBRh8F6fDGCCEIPk9Hb0cEyB.jpg",
  cast: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Geoffrey Rush"],
  streaming: ["Disney+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "potc-4",
  title: "Pirates of the Caribbean: On Stranger Tides",
  year: 2011,
  universe: "Other",
  category: "movie",
  genre: "Adventure / Fantasy",
  rating: 6.6,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/keGfSvCmYj7CvdRx36OdVrAEibE.jpg",
  cast: ["Johnny Depp", "Penélope Cruz", "Geoffrey Rush", "Ian McShane"],
  streaming: ["Disney+", "Prime Video (rental)", "Apple TV (rental)"]
}),
m({
  id: "potc-5",
  title: "Pirates of the Caribbean: Dead Men Tell No Tales",
  year: 2017,
  universe: "Other",
  category: "movie",
  genre: "Adventure / Fantasy",
  rating: 6.5,
  poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/xbpSDU3p7YUGlu9Mr6Egg2Vweto.jpg",
  cast: ["Johnny Depp", "Javier Bardem", "Geoffrey Rush", "Brenton Thwaites"],
  streaming: ["Disney+", "Prime Video (rental)", "Apple TV (rental)"]
}),

]