// src/moviesData.js

// --- MOVIES ---------------------------------------------------------

export const movies = [
  // ===== MARVEL (MCU & related) =====
  {
    id: "iron-man-1",
    title: "Iron Man",
    franchise: "Marvel",
    type: "Movie",
    year: 2008,
    rating: 7.9,
    runtime: "2h 6m",
    genres: ["Action", "Sci-Fi", "Superhero"],
    directors: ["Jon Favreau"],
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges"],
    plot:
      "Billionaire engineer Tony Stark builds a high-tech suit of armor to escape captivity and becomes the armored hero Iron Man.",
    streaming: ["Disney+"],
  },
  {
    id: "iron-man-2",
    title: "Iron Man 2",
    franchise: "Marvel",
    type: "Movie",
    year: 2010,
    rating: 7.0,
    runtime: "2h 4m",
    genres: ["Action", "Sci-Fi", "Superhero"],
    directors: ["Jon Favreau"],
    cast: ["Robert Downey Jr.", "Scarlett Johansson", "Mickey Rourke"],
    plot:
      "Tony faces government pressure, a rival weapons developer and a vengeful physicist who builds his own arc-powered weapons.",
    streaming: ["Disney+"],
  },
  {
    id: "iron-man-3",
    title: "Iron Man 3",
    franchise: "Marvel",
    type: "Movie",
    year: 2013,
    rating: 7.1,
    runtime: "2h 10m",
    genres: ["Action", "Sci-Fi", "Superhero"],
    directors: ["Shane Black"],
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Guy Pearce"],
    plot:
      "Traumatized after the Battle of New York, Tony confronts a global terrorist known as the Mandarin and his own dependence on the suit.",
    streaming: ["Disney+"],
  },
  {
    id: "cap-am-1",
    title: "Captain America: The First Avenger",
    franchise: "Marvel",
    type: "Movie",
    year: 2011,
    rating: 6.9,
    runtime: "2h 4m",
    genres: ["Action", "Adventure", "Superhero"],
    directors: ["Joe Johnston"],
    cast: ["Chris Evans", "Hayley Atwell", "Hugo Weaving"],
    plot:
      "Steve Rogers volunteers for a top-secret experiment that turns him into the super-soldier Captain America during World War II.",
    streaming: ["Disney+"],
  },
  {
    id: "avengers-2012",
    title: "The Avengers",
    franchise: "Marvel",
    type: "Movie",
    year: 2012,
    rating: 8.0,
    runtime: "2h 23m",
    genres: ["Action", "Superhero"],
    directors: ["Joss Whedon"],
    cast: [
      "Robert Downey Jr.",
      "Chris Evans",
      "Scarlett Johansson",
      "Chris Hemsworth",
    ],
    plot:
      "Nick Fury unites Earth's mightiest heroes to stop Loki and an alien invasion of New York City.",
    streaming: ["Disney+"],
  },
  {
    id: "cap-winter-soldier",
    title: "Captain America: The Winter Soldier",
    franchise: "Marvel",
    type: "Movie",
    year: 2014,
    rating: 7.8,
    runtime: "2h 16m",
    genres: ["Action", "Thriller", "Superhero"],
    directors: ["Anthony Russo", "Joe Russo"],
    cast: [
      "Chris Evans",
      "Scarlett Johansson",
      "Sebastian Stan",
      "Anthony Mackie",
    ],
    plot:
      "Steve Rogers uncovers a Hydra conspiracy inside S.H.I.E.L.D. while facing a deadly assassin known as the Winter Soldier.",
    streaming: ["Disney+"],
  },
  {
    id: "guardians-1",
    title: "Guardians of the Galaxy",
    franchise: "Marvel",
    type: "Movie",
    year: 2014,
    rating: 8.0,
    runtime: "2h 1m",
    genres: ["Action", "Sci-Fi", "Comedy"],
    directors: ["James Gunn"],
    cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista"],
    plot:
      "A band of misfits led by Peter Quill must stop Ronan the Accuser with the help of an orb that holds an Infinity Stone.",
    streaming: ["Disney+"],
  },
  {
    id: "avengers-age-ultron",
    title: "Avengers: Age of Ultron",
    franchise: "Marvel",
    type: "Movie",
    year: 2015,
    rating: 7.3,
    runtime: "2h 21m",
    genres: ["Action", "Superhero"],
    directors: ["Joss Whedon"],
    cast: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
    plot:
      "Tony Stark's peacekeeping AI, Ultron, becomes sentient and decides humanity must be eradicated, forcing the Avengers to unite again.",
    streaming: ["Disney+"],
  },
  {
    id: "cap-civil-war",
    title: "Captain America: Civil War",
    franchise: "Marvel",
    type: "Movie",
    year: 2016,
    rating: 7.8,
    runtime: "2h 27m",
    genres: ["Action", "Superhero"],
    directors: ["Anthony Russo", "Joe Russo"],
    cast: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson"],
    plot:
      "Government oversight splits the Avengers into opposing factions led by Iron Man and Captain America.",
    streaming: ["Disney+"],
  },
  {
    id: "black-panther",
    title: "Black Panther",
    franchise: "Marvel",
    type: "Movie",
    year: 2018,
    rating: 7.3,
    runtime: "2h 14m",
    genres: ["Action", "Adventure", "Superhero"],
    directors: ["Ryan Coogler"],
    cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
    plot:
      "T'Challa returns home to Wakanda to become king but faces a powerful challenger with a claim to the throne.",
    streaming: ["Disney+"],
  },
  {
    id: "avengers-infinity-war",
    title: "Avengers: Infinity War",
    franchise: "Marvel",
    type: "Movie",
    year: 2018,
    rating: 8.4,
    runtime: "2h 29m",
    genres: ["Action", "Sci-Fi", "Superhero"],
    directors: ["Anthony Russo", "Joe Russo"],
    cast: [
      "Robert Downey Jr.",
      "Chris Hemsworth",
      "Chris Evans",
      "Josh Brolin",
    ],
    plot:
      "The Avengers and their allies attempt to stop Thanos from acquiring the Infinity Stones and erasing half of all life.",
    streaming: ["Disney+"],
  },
  {
    id: "avengers-endgame",
    title: "Avengers: Endgame",
    franchise: "Marvel",
    type: "Movie",
    year: 2019,
    rating: 8.4,
    runtime: "3h 1m",
    genres: ["Action", "Sci-Fi", "Superhero"],
    directors: ["Anthony Russo", "Joe Russo"],
    cast: [
      "Robert Downey Jr.",
      "Chris Evans",
      "Scarlett Johansson",
      "Mark Ruffalo",
    ],
    plot:
      "After Thanos' snap, the remaining heroes plan a risky time-heist to restore everyone who vanished.",
    streaming: ["Disney+"],
  },
  {
    id: "no-way-home",
    title: "Spider-Man: No Way Home",
    franchise: "Marvel",
    type: "Movie",
    year: 2021,
    rating: 8.2,
    runtime: "2h 28m",
    genres: ["Action", "Superhero"],
    directors: ["Jon Watts"],
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    plot:
      "A spell gone wrong tears open the multiverse, bringing in villains and Spider-Men from other realities.",
    streaming: ["Disney+", "Netflix (varies by region)"],
  },

  // ===== DC =====
  {
    id: "batman-begins",
    title: "Batman Begins",
    franchise: "DC",
    type: "Movie",
    year: 2005,
    rating: 8.2,
    runtime: "2h 20m",
    genres: ["Action", "Superhero"],
    directors: ["Christopher Nolan"],
    cast: ["Christian Bale", "Michael Caine", "Liam Neeson"],
    plot:
      "Bruce Wayne trains with the League of Shadows and returns to Gotham to become Batman.",
    streaming: ["Max"],
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    franchise: "DC",
    type: "Movie",
    year: 2008,
    rating: 9.0,
    runtime: "2h 32m",
    genres: ["Action", "Crime", "Superhero"],
    directors: ["Christopher Nolan"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Gary Oldman"],
    plot:
      "Batman faces the Joker, a sadistic criminal mastermind who wants to push Gotham into chaos.",
    streaming: ["Max"],
  },
  {
    id: "the-dark-knight-rises",
    title: "The Dark Knight Rises",
    franchise: "DC",
    type: "Movie",
    year: 2012,
    rating: 8.4,
    runtime: "2h 44m",
    genres: ["Action", "Thriller", "Superhero"],
    directors: ["Christopher Nolan"],
    cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway"],
    plot:
      "Eight years after taking the fall for Harvey Dent, Batman returns to face the merciless Bane.",
    streaming: ["Max"],
  },
  {
    id: "man-of-steel",
    title: "Man of Steel",
    franchise: "DC",
    type: "Movie",
    year: 2013,
    rating: 7.1,
    runtime: "2h 23m",
    genres: ["Action", "Sci-Fi", "Superhero"],
    directors: ["Zack Snyder"],
    cast: ["Henry Cavill", "Amy Adams", "Michael Shannon"],
    plot:
      "Kal-El embraces his destiny as Superman when General Zod arrives to conquer Earth.",
    streaming: ["Max"],
  },
  {
    id: "wonder-woman",
    title: "Wonder Woman",
    franchise: "DC",
    type: "Movie",
    year: 2017,
    rating: 7.4,
    runtime: "2h 21m",
    genres: ["Action", "Fantasy", "Superhero"],
    directors: ["Patty Jenkins"],
    cast: ["Gal Gadot", "Chris Pine", "Robin Wright"],
    plot:
      "Amazon warrior Diana leaves her hidden island to stop a devastating war and discovers her divine powers.",
    streaming: ["Max"],
  },
  {
    id: "justice-league",
    title: "Zack Snyder's Justice League",
    franchise: "DC",
    type: "Movie",
    year: 2021,
    rating: 8.0,
    runtime: "4h 2m",
    genres: ["Action", "Superhero"],
    directors: ["Zack Snyder"],
    cast: [
      "Ben Affleck",
      "Henry Cavill",
      "Gal Gadot",
      "Jason Momoa",
      "Ezra Miller",
    ],
    plot:
      "Bruce Wayne and Diana Prince assemble a team of metahumans to defend Earth from the alien warlord Steppenwolf.",
    streaming: ["Max"],
  },
  {
    id: "the-batman-2022",
    title: "The Batman",
    franchise: "DC",
    type: "Movie",
    year: 2022,
    rating: 7.8,
    runtime: "2h 56m",
    genres: ["Crime", "Mystery", "Superhero"],
    directors: ["Matt Reeves"],
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
    plot:
      "In his second year of crime-fighting, Batman hunts a sadistic killer known as the Riddler in a grim, noir-style Gotham.",
    streaming: ["Max"],
  },

  // ===== STAR WARS (films) =====
  {
    id: "sw-iv",
    title: "Star Wars: A New Hope",
    franchise: "Star Wars",
    type: "Movie",
    year: 1977,
    rating: 8.6,
    runtime: "2h 1m",
    genres: ["Sci-Fi", "Adventure"],
    directors: ["George Lucas"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    plot:
      "Farm boy Luke Skywalker joins the Rebel Alliance to destroy the Death Star and save the galaxy.",
    streaming: ["Disney+"],
  },
  {
    id: "sw-v",
    title: "The Empire Strikes Back",
    franchise: "Star Wars",
    type: "Movie",
    year: 1980,
    rating: 8.7,
    runtime: "2h 4m",
    genres: ["Sci-Fi", "Adventure"],
    directors: ["Irvin Kershner"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    plot:
      "The Empire relentlessly pursues the Rebels while Luke seeks advanced Jedi training from Yoda.",
    streaming: ["Disney+"],
  },
  {
    id: "sw-vi",
    title: "Return of the Jedi",
    franchise: "Star Wars",
    type: "Movie",
    year: 1983,
    rating: 8.3,
    runtime: "2h 11m",
    genres: ["Sci-Fi", "Adventure"],
    directors: ["Richard Marquand"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    plot:
      "Luke confronts Darth Vader and the Emperor while the Rebel Alliance attacks a second Death Star.",
    streaming: ["Disney+"],
  },
  {
    id: "sw-vii",
    title: "The Force Awakens",
    franchise: "Star Wars",
    type: "Movie",
    year: 2015,
    rating: 7.8,
    runtime: "2h 18m",
    genres: ["Sci-Fi", "Adventure"],
    directors: ["J. J. Abrams"],
    cast: ["Daisy Ridley", "John Boyega", "Harrison Ford", "Adam Driver"],
    plot:
      "A new threat called the First Order rises as scavenger Rey discovers her own connection to the Force.",
    streaming: ["Disney+"],
  },
  {
    id: "rogue-one",
    title: "Rogue One: A Star Wars Story",
    franchise: "Star Wars",
    type: "Movie",
    year: 2016,
    rating: 7.8,
    runtime: "2h 13m",
    genres: ["Sci-Fi", "War"],
    directors: ["Gareth Edwards"],
    cast: ["Felicity Jones", "Diego Luna", "Ben Mendelsohn"],
    plot:
      "A band of Rebels undertakes a desperate mission to steal the plans for the Death Star.",
    streaming: ["Disney+"],
  },
  {
    id: "sw-ix",
    title: "The Rise of Skywalker",
    franchise: "Star Wars",
    type: "Movie",
    year: 2019,
    rating: 6.5,
    runtime: "2h 22m",
    genres: ["Sci-Fi", "Adventure"],
    directors: ["J. J. Abrams"],
    cast: ["Daisy Ridley", "Adam Driver", "Oscar Isaac"],
    plot:
      "The Resistance faces the resurrected Emperor Palpatine as Rey confronts her mysterious lineage.",
    streaming: ["Disney+"],
  },

  // ===== INDIANA JONES =====
  {
    id: "raiders",
    title: "Raiders of the Lost Ark",
    franchise: "Indiana Jones",
    type: "Movie",
    year: 1981,
    rating: 8.4,
    runtime: "1h 55m",
    genres: ["Adventure", "Action"],
    directors: ["Steven Spielberg"],
    cast: ["Harrison Ford", "Karen Allen", "Paul Freeman"],
    plot:
      "Archaeologist Indiana Jones races Nazi forces to recover the biblical Ark of the Covenant.",
    streaming: ["Disney+"],
  },
  {
    id: "temple-of-doom",
    title: "Indiana Jones and the Temple of Doom",
    franchise: "Indiana Jones",
    type: "Movie",
    year: 1984,
    rating: 7.5,
    runtime: "1h 58m",
    genres: ["Adventure", "Action"],
    directors: ["Steven Spielberg"],
    cast: ["Harrison Ford", "Kate Capshaw", "Ke Huy Quan"],
    plot:
      "Indy, Willie and Short Round uncover a dark cult in India that enslaves children and worships Kali.",
    streaming: ["Disney+"],
  },
  {
    id: "last-crusade",
    title: "Indiana Jones and the Last Crusade",
    franchise: "Indiana Jones",
    type: "Movie",
    year: 1989,
    rating: 8.2,
    runtime: "2h 7m",
    genres: ["Adventure", "Action"],
    directors: ["Steven Spielberg"],
    cast: ["Harrison Ford", "Sean Connery", "Denholm Elliott"],
    plot:
      "Indy joins his father on a quest to find the Holy Grail before the Nazis can obtain it.",
    streaming: ["Disney+"],
  },
  {
    id: "dial-of-destiny",
    title: "Indiana Jones and the Dial of Destiny",
    franchise: "Indiana Jones",
    type: "Movie",
    year: 2023,
    rating: 6.6,
    runtime: "2h 34m",
    genres: ["Adventure", "Action"],
    directors: ["James Mangold"],
    cast: ["Harrison Ford", "Phoebe Waller-Bridge", "Mads Mikkelsen"],
    plot:
      "An aging Indiana Jones teams up with his goddaughter to recover a powerful time-related artifact.",
    streaming: ["Disney+"],
  },
];

// --- SERIES ---------------------------------------------------------

export const series = [
  // ===== MARVEL SERIES =====
  {
    id: "wandavision",
    title: "WandaVision",
    franchise: "Marvel",
    type: "Series",
    years: "2021",
    rating: 7.9,
    seasons: 1,
    genres: ["Superhero", "Mystery", "Sitcom"],
    cast: ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn"],
    plot:
      "Wanda and Vision live in a shifting sitcom reality that hides a deeper grief-driven mystery.",
    streaming: ["Disney+"],
  },
  {
    id: "falcon-winter-soldier",
    title: "The Falcon and the Winter Soldier",
    franchise: "Marvel",
    type: "Series",
    years: "2021",
    rating: 7.2,
    seasons: 1,
    genres: ["Superhero", "Action"],
    cast: ["Anthony Mackie", "Sebastian Stan", "Wyatt Russell"],
    plot:
      "Sam Wilson and Bucky Barnes team up to confront Flag-Smashers and a new, unstable Captain America.",
    streaming: ["Disney+"],
  },
  {
    id: "loki",
    title: "Loki",
    franchise: "Marvel",
    type: "Series",
    years: "2021–2023",
    rating: 8.2,
    seasons: 2,
    genres: ["Superhero", "Sci-Fi"],
    cast: ["Tom Hiddleston", "Owen Wilson", "Sophia Di Martino"],
    plot:
      "A variant Loki works with the TVA to fix branching timelines and confront multiverse-level threats.",
    streaming: ["Disney+"],
  },
  {
    id: "hawkeye",
    title: "Hawkeye",
    franchise: "Marvel",
    type: "Series",
    years: "2021",
    rating: 7.5,
    seasons: 1,
    genres: ["Superhero", "Action"],
    cast: ["Jeremy Renner", "Hailee Steinfeld", "Florence Pugh"],
    plot:
      "Clint Barton teams up with energetic archer Kate Bishop during a chaotic Christmas in New York.",
    streaming: ["Disney+"],
  },
  {
    id: "moon-knight",
    title: "Moon Knight",
    franchise: "Marvel",
    type: "Series",
    years: "2022",
    rating: 7.3,
    seasons: 1,
    genres: ["Superhero", "Psychological"],
    cast: ["Oscar Isaac", "Ethan Hawke", "May Calamawy"],
    plot:
      "A man with dissociative identity disorder becomes the avatar of the Egyptian moon god Khonshu.",
    streaming: ["Disney+"],
  },

  // ===== DC SERIES =====
  {
    id: "arrow",
    title: "Arrow",
    franchise: "DC",
    type: "Series",
    years: "2012–2020",
    rating: 7.5,
    seasons: 8,
    genres: ["Superhero", "Action"],
    cast: ["Stephen Amell", "Katie Cassidy", "Emily Bett Rickards"],
    plot:
      "Billionaire Oliver Queen returns from five brutal years and becomes the vigilante Green Arrow.",
    streaming: ["Netflix", "Max (varies by region)"],
  },
  {
    id: "the-flash",
    title: "The Flash",
    franchise: "DC",
    type: "Series",
    years: "2014–2023",
    rating: 7.4,
    seasons: 9,
    genres: ["Superhero", "Sci-Fi"],
    cast: ["Grant Gustin", "Candice Patton", "Danielle Panabaker"],
    plot:
      "Forensic scientist Barry Allen gains super speed and becomes Central City's scarlet speedster.",
    streaming: ["Netflix", "Max (varies by region)"],
  },
  {
    id: "peacemaker",
    title: "Peacemaker",
    franchise: "DC",
    type: "Series",
    years: "2022–",
    rating: 8.3,
    seasons: 1,
    genres: ["Superhero", "Comedy"],
    cast: ["John Cena", "Danielle Brooks", "Freddie Stroma"],
    plot:
      "Anti-hero Peacemaker joins a black-ops team to stop a bizarre alien threat while dealing with his toxic upbringing.",
    streaming: ["Max"],
  },

  // ===== STAR WARS SERIES =====
  {
    id: "the-mandalorian",
    title: "The Mandalorian",
    franchise: "Star Wars",
    type: "Series",
    years: "2019–",
    rating: 8.7,
    seasons: 3,
    genres: ["Sci-Fi", "Adventure"],
    cast: ["Pedro Pascal", "Katee Sackhoff"],
    plot:
      "A lone bounty hunter in the Outer Rim protects a mysterious child wanted by Imperial remnants.",
    streaming: ["Disney+"],
  },
  {
    id: "the-book-of-boba-fett",
    title: "The Book of Boba Fett",
    franchise: "Star Wars",
    type: "Series",
    years: "2021–2022",
    rating: 7.2,
    seasons: 1,
    genres: ["Sci-Fi", "Adventure"],
    cast: ["Temuera Morrison", "Ming-Na Wen"],
    plot:
      "Bounty hunter Boba Fett and Fennec Shand attempt to rule Jabba's former territory on Tatooine.",
    streaming: ["Disney+"],
  },
  {
    id: "obi-wan-kenobi",
    title: "Obi-Wan Kenobi",
    franchise: "Star Wars",
    type: "Series",
    years: "2022",
    rating: 7.0,
    seasons: 1,
    genres: ["Sci-Fi", "Adventure"],
    cast: ["Ewan McGregor", "Hayden Christensen", "Vivien Lyra Blair"],
    plot:
      "A weary Obi-Wan watches over young Luke until events force him to face Darth Vader again.",
    streaming: ["Disney+"],
  },
  {
    id: "andor",
    title: "Andor",
    franchise: "Star Wars",
    type: "Series",
    years: "2022–",
    rating: 8.4,
    seasons: 1,
    genres: ["Sci-Fi", "Thriller"],
    cast: ["Diego Luna", "Stellan Skarsgård", "Genevieve O'Reilly"],
    plot:
      "Cassian Andor is drawn into the early Rebellion in a grounded, espionage-style Star Wars story.",
    streaming: ["Disney+"],
  },
  {
    id: "clone-wars",
    title: "Star Wars: The Clone Wars",
    franchise: "Star Wars",
    type: "Series",
    years: "2008–2020",
    rating: 8.4,
    seasons: 7,
    genres: ["Animation", "Sci-Fi"],
    cast: ["Matt Lanter", "Ashley Eckstein", "James Arnold Taylor"],
    plot:
      "Animated adventures reveal the conflicts between Episodes II and III, following Anakin, Ahsoka and Obi-Wan.",
    streaming: ["Disney+"],
  },

  // ===== INDIANA JONES SERIES =====
  {
    id: "young-indy",
    title: "The Young Indiana Jones Chronicles",
    franchise: "Indiana Jones",
    type: "Series",
    years: "1992–1993",
    rating: 7.2,
    seasons: 2,
    genres: ["Adventure"],
    cast: ["Sean Patrick Flanery", "Corey Carrier", "George Hall"],
    plot:
      "Anthology series following Indiana Jones through his childhood and teenage adventures around the world.",
    streaming: ["Paramount+ / Disney+ (varies by region)"],
  },
];
